lidShapes = {
    'baseMesh': 'Character' ,
    'Type':'blendShapeDefinition',
    'control' : 'Character_LF_EyeLidShapes00_ctr_facialRig',
    "blendShapes":{
                "UpperEyeLidSpinCW" : {"connection": "UpLidSpin"       ,"value":  10},
                "UpperEyeLidSpinCCW": {"connection": "UpLidSpin"       ,"value": -10},
                "LowerEyeLidSpinCW" : {"connection": "LowLidSpin"      ,"value":  10},
                "LowerEyeLidSpinCCW": {"connection": "LowLidSpin"      ,"value": -10},
                #"EyeSpinCCW"       : {"connection": "Spin"            ,"value":  10},
                #"EyeSpinCW"        : {"connection": "Spin"            ,"value": -10},
                "Bulge"             : {"connection": "Bulge"           ,"value":  10},
                "UpperSquint"       : {"connection": "UpperSquint"     ,"value":  10},
                "LowerSquint"       : {"connection": "LowerSquint"     ,"value":  10},
                "UpLidInnerUp"      : {"connection": "UpLidInnerUD"    ,"value":  10},
                "UpLidInnerDn"      : {"connection": "UpLidInnerUD"    ,"value": -10},
                "UpLidMidUp"        : {"connection": "UpLidMidUD"      ,"value":  10},
                "UpLidMidDown"      : {"connection": "UpLidMidUD"      ,"value": -10},
                "UpLidOuterUp"      : {"connection": "UpLidOuterUD"    ,"value":  10},
                "UpLidOuterDown"    : {"connection": "UpLidOuterUD"    ,"value": -10},

                "LowLidInnerUp"     : {"connection": "LowLidInnerUD"   ,"value":  10},
                "LowLidInnerDown"   : {"connection": "LowLidInnerUD"   ,"value": -10},
                "LowLidMidUp"       : {"connection": "LowLidMidUD"     ,"value":  10},
                "LowLidMidDown"     : {"connection": "LowLidMidUD"     ,"value": -10},
                "LowLidOuterUp"     : {"connection": "LowLidOuterUD"   ,"value":  10},
                "LowLidOuterDown"   : {"connection": "LowLidOuterUD"   ,"value": -10},
                
                "CornerInnerUp"     : {"connection": "CornerOuterUD"   ,"value":  10},
                "CornerOuterUp"     : {"connection": "CornerOuterUD"   ,"value":  10},
    
                "UpLidDn"           : {"connection": "UpLidUD"         ,"value":  10},
                "UpLidDnHalf"       : {"connection": "UpLidUD"         ,"value":   5},
                "UpLidUp"           : {"connection": "UpLidUD"         ,"value": -10},
                "LowLidUp"          : {"connection": "LowLidUD"        ,"value":  10},
                "LowLidUpHalf"      : {"connection": "LowLidUD"        ,"value":   5},
                "LowLidDn"          : {"connection": "LowLidUD"        ,"value": -10}},
    "attributes" : {
                     'UpLidUD'       :{"type": "float", "min": -10, "max":10},
                     'LowLidUD'      :{"type": "float", "min": -10, "max":10},
                     'UpLidSpin'     :{"type": "float", "min": -10, "max":10}, 
                     'LowLidSpin'    :{"type": "float", "min": -10, "max":10},
                     'Spin'          :{"type": "float", "min": -10, "max":10},
                     'UpLidInOut'    :{"type": "float", "min": -10, "max":10},
                     'LowLidInOut'   :{"type": "float", "min": -10, "max":10},
                     'Bulge'         :{"type": "float", "min":   0, "max":10}, 
                     'UpperSquint'   :{"type": "float", "min":   0, "max":10}, 
                     'LowerSquint'   :{"type": "float", "min":   0, "max":10},
                     'UpLidInnerUD'  :{"type": "float", "min": -10, "max":10}, 
                     'UpLidMidUD'    :{"type": "float", "min": -10, "max":10}, 
                     'UpLidOuterUD'  :{"type": "float", "min": -10, "max":10}, 
                     'LowLidInnerUD' :{"type": "float", "min": -10, "max":10}, 
                     'LowLidMidUD'   :{"type": "float", "min": -10, "max":10}, 
                     'LowLidOuterUD' :{"type": "float", "min": -10, "max":10}, 
                     'CornerInnerUD' :{"type": "float", "min":   0, "max":10}, 
                     'CornerOuterUD' :{"type": "float", "min":   0, "max":10}},

    'order':    ['UpLidUD','LowLidUD','UpLidSpin','LowLidSpin','Spin','UpLidInOut','LowLidInOut',
                 'Bulge','UpperSquint','LowerSquint','UpLidInnerUD','UpLidMidUD',
                 'UpLidOuterUD','LowLidInnerUD','LowLidMidUD' ,'LowLidOuterUD','CornerInnerUD',
                 'CornerOuterUD']
    }

EyeBallPupil = {"EyeBall":{'Type'         : 'blendShapeDefinition',
                           'baseMesh'     : 'LEyeBall',
                           'isSymetrical' : True,
                           'control'      : 'Character_LF_EyeLidShapes00_ctr_facialRig',
                           'blendShapes'  : {'irisContract'      : {"connection":"Iris",   "value": -10},
                                            'irisExpand'         : {"connection":"Iris",   "value":  10},
                                            'PupilContract'      : {"connection":"Pupil",  "value": -10},
                                            'PupilExpand'        : {"connection":"Pupil",  "value":  10}},
                           'attributes'   : {'Iris'         : {"type": "float", "min":-10, "max":10},
                                            'Pupil'         : {"type": "float", "min":-10, "max":10}},            
                           'order'        : ['Iris','Pupil']}
              }

Cristaline = {"Diverge":{
                            'Type':"blendShapeDefinition",
                            "isSymetrical":True,
                            "baseMesh"    : 'Crystalline',

                            "control"     : "Character_LF_EyeLidShapes00_ctr_facialRig",

                            "attributes"  : {'PupilDivergeUD':{"type": "float", "min":-10, "max":10},
                                             'PupilDivergeLR':{"type": "float", "min":-10, "max":10}},

                            "blendShapes" : {  'PupilDivergeUp'      : {"connection":"PupilDivergeUD"  ,"value":  10},
                                               'PupilDivergeDn'      : {"connection":"PupilDivergeUD"  ,"value": -10},
                                               'PupilDivergeLf'      : {"connection":"PupilDivergeLR"  ,"value":  10},
                                               'PupilDivergeRh'      : {"connection":"PupilDivergeLR"  ,"value": -10}},
                            'order'       : ['PupilDivergeUD' , 'PupilDivergeLR']
                          }
            }

mouthSecondarys = {"lipUpperMidSecondary":{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_RH_MidUpLip00_ctr_facialRig",
                                "attributes"  :{"UD"     :{"type": "float", "min":-10, "max":10},
                                                "FB"     :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'UpperMidUp' : {"connection":"UD"  ,"value":  10},
                                                'UpperMidDn' : {"connection":"UD"  ,"value": -10},
                                                'UpperMidFn' : {"connection":"FB"  ,"value":  10},
                                                'UpperMidBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']},
                    "lipLowMidSecondary" :{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_RH_MidLowLip00_ctr_facialRig",
                                "attributes"  :{"UD"     :{"type": "float", "min":-10, "max":10},
                                                "FB"     :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'LowMidUp' : {"connection":"UD"  ,"value":  10},
                                                'LowMidDn' : {"connection":"UD"  ,"value": -10},
                                                'LowMidFn' : {"connection":"FB"  ,"value":  10},
                                                'LowMidBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']},
                    "LipCornerSecondary" :{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_RH_CornerLip00_ctr_facialRig",
                                "attributes"  :{"UD"       : {"type": "float", "min":-10, "max":10},
                                                "FB"       : {"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'CornerUp' : {"connection":"UD"  ,"value":  10},
                                                'CornerDn' : {"connection":"UD"  ,"value": -10},
                                                'CornerFn' : {"connection":"FB"  ,"value":  10},
                                                'CornerBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']},
                    "LipUpperSecondary" :{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":False,
                                "baseMesh"    : "Character",
                                "control"     : "Character_MD_MidLowLip00_ctr_facialRig",
                                "attributes"  :{"UD"     :{"type": "float", "min":-10, "max":10},
                                                "FB"     :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'LowUp' : {"connection":"UD"  ,"value":  10},
                                                'LowDn' : {"connection":"UD"  ,"value": -10},
                                                'LowFn' : {"connection":"FB"  ,"value":  10},
                                                'LowBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']},
                    "LipLowSecondary" :{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":False,
                                "baseMesh"    : "Character",
                                "control"     : "Character_MD_MidUpLip00_ctr_facialRig",
                                "attributes"  :{"UD"     :{"type": "float", "min":-10, "max":10},
                                                "FB"     :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'UpperUp' : {"connection":"UD"  ,"value":  10},
                                                'UpperDn' : {"connection":"UD"  ,"value": -10},
                                                'UpperFn' : {"connection":"FB"  ,"value":  10},
                                                'UpperBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']}
              }
EyeJawJoints = { "lidJoints":{
                    'Type'        : "jointLinkDefinition",
                    'isSymetrical': True,
                    'control'     :  'Character_LF_EyeLidShapes00_ctr_facialRig',
                    'joints'      : {'Character_LF_EyeUpperLid00_sknjnt_Rig':{"connection":"UpLidUD" , "inputPlug":"rotateY","value" : [[-10, -45] ,[0,0] ,[10, 16]]},
                                     "Character_LF_EyeLowerLid00_sknjnt_Rig":{"connection":"LowLidUD", "inputPlug":"rotateY","value" : [[-10,  16] ,[0,0] ,[10,-45]]},
                                     "Character_LF_EyeLidSpin00_grp_Rig"    :{"connection":"spin"    , "inputPlug":"rotateX","value" : [[-10, -45] ,[0,0] ,[10,45]]}},
                    "attributes"  : {"UpLidUD"      :{"type": "float", "min":-10, "max":10},
                                     "LowLidUD"     :{"type": "float", "min":-10, "max":10},
                                     "spin"         :{"type": "float", "min":-10, "max":10}},
                    'order'       : ['UpLidUD' , 'LowLidUD', 'spin']},
                "jawjoint":{
                    'Type'        : "jointLinkDefinition",
                    'isSymetrical': False,
                    'control'     : 'Character_MD_Jaw00_ctr_rig',
                    'joints'      : {"Character_MD_Jaw_sknjnt_RIG":{"connection":"rotateZ" , "inputPlug":"rotateZ", "value" : None}},
                    'attributes'  : {'rotateZ':{}},
                    'order'       : ['rotateZ']}
                }

mouth = { "mouthMain":{
                    'Type'        : "jointLinkDefinition",
                    'isSymetrical': False,
                    'control'     :  'Character_LF_EyeLidShapes00_ctr_facialRig',
                    'blendShapes' :{{'Smile'        : {"connection":"SmileFrown"    ,"value":  10},
                                     'Frown'        : {"connection":"SmileFrown"    ,"value": -10},
                                     'Wide'         : {"connection":"NarrowWide"    ,"value":  10},
                                     'Narrow'       : {"connection":"NarrowWide"    ,"value": -10},
                                     #'Ooo'          : {"connection":"Ooo"           ,"value":  10},
                                     'CornerUp'     : {"connection":"CornerUD"      ,"value":  10},
                                     #'CornerDn'     : {"connection":"CornerUD"      ,"value": -10},
                                     #'Pinch'        : {"connection":"Pinch"         ,"value":  10},
                                     #'LSmile'       : {"connection":"SmileFrownL"   ,"value":  10},
                                     #'LFrown'       : {"connection":"SmileFrownL"   ,"value": -10},
                                     #'RSmile'       : {"connection":"SmileFrownR"   ,"value":  10},
                                     #'RFrown'       : {"connection":"SmileFrownR"   ,"value": -10},
                                     #'LWide'        : {"connection":"NarrowWideL"   ,"value":  10},
                                     #'LNarrow'      : {"connection":"NarrowWideL"   ,"value": -10},
                                     #'RWide'        : {"connection":"NarrowWideR"   ,"value":  10},
                                     #'RNarrow'      : {"connection":"NarrowWideR"   ,"value": -10},
                                     #'LCornerUp'    : {"connection":"CornerL"       ,"value":  10},
                                     #'LCornerDn'    : {"connection":"CornerL"       ,"value": -10},
                                     #'RCornerUp'    : {"connection":"CornerR"       ,"value":  10},
                                     #'RCornerDn'    : {"connection":"CornerR"       ,"value": -10},
                                     #'Lpinch'       : {"connection":"PinchL"        ,"value":  10},
                                     #'Rpinch'       : {"connection":"PinchR"        ,"value":  10},
                                     #'LUpperSneer'  : {"connection":"UpperLipSneerL","value":  10},
                                     #'RUpperSneer'  : {"connection":"UpperLipSneerR","value":  10},
                                     #'MUpperSneerUp': {"connection":"UpperLipMidUD" ,"value": -10},
                                     #'MUpperSneerDn': {"connection":"UpperLipMidUD" ,"value":  10},
                                     #'LLowSneer'    : {"connection":"LowerLipSneerL","value":  10},
                                     #'RLowSneer'    : {"connection":"LowerLipSneerR","value":  10},
                                     #'LowSneerUp'  : {"connection":"LowerLipSneerUD","value": -10},
                                     #'LowSneerDn'  : {"connection":"LowerLipSneerUD","value":  10},

                                   }


                                    },
                    'attributes'  :{'SmileFrown'     :{"type": "float", "min":-10, "max":10}, 
                                    'NarrowWide'     :{"type": "float", "min":-10, "max":10},
                                    'Ooo'            :{"type": "float", "min":  0, "max":10},
                                    #'Press'          :{"type": "float", "min":  0, "max":10}, 
                                    #'Puff'           :{"type": "float", "min":  0, "max":10},
                                    'CornerUD'       :{"type": "float", "min":-10, "max":10},
                                    'Pinch'          :{"type": "float", "min":  0, "max":10},
                                    'LeftRightShapes':{"type": "float", "min":  0, "max":10, "keyable" : False },
                                    'SmileFrownL'    :{"type": "float", "min":-10, "max":10}, 
                                    'SmileFrownR'    :{"type": "float", "min":-10, "max":10}, 
                                    'NarrowWideL'    :{"type": "float", "min":-10, "max":10}, 
                                    'NarrowWideR'    :{"type": "float", "min":-10, "max":10}, 
                                    'CornerL'        :{"type": "float", "min":-10, "max":10}, 
                                    'CornerR'        :{"type": "float", "min":-10, "max":10}, 
                                    'PinchL'         :{"type": "float", "min":  0, "max":10},
                                    'PinchR'         :{"type": "float", "min":  0, "max":10},
                                    'UpperLip'       :{"type": "float", "min":  0, "max":10, "keyable" : False },
                                    'UpperLipSneerL' :{"type": "float", "min":  0, "max":10},
                                    'UpperLipSneerR' :{"type": "float", "min":  0, "max":10},
                                    'UpperLipMidUD'  :{"type": "float", "min":-10, "max":10}, 
                                    'LowerLip'       :{"type": "float", "min":  0, "max":10, "keyable" : False },
                                    'LowerLipSneerL' :{"type": "float", "min":  0, "max":10},
                                    'LowerLipSneerR' :{"type": "float", "min":  0, "max":10},
                                    'LowerLipMidUD'  :{"type": "float", "min":-10, "max":10}, 
                                    'Jaw'            :{"type": "float", "min":  0, "max":10, "keyable" : False },
                                    'StickyLips'     :{"type": "float", "min":  0, "max":10}}
                      'order'     :['SmileFrown','NarrowWide','Ooo','Press','Puff','CornerUD','Pinch','LeftRightShapes',
                                    'SmileFrownL','SmileFrownR','NarrowWideL','NarrowWideR','CornerL','CornerR','PinchL',
                                    'CornerR','PinchL','PinchR','UpperLip','UpperLipSneerL','UpperLipSneerR','UpperLipMidUD',
                                    'UpperLipMidUD','LowerLip','LowerLipSneerL','LowerLipSneerR','LowerLipMidUD','Jaw','StickyLips']}
}

