lidShapes = {"lidShapes":{
                            'baseMesh': 'Character' ,
                            'Type':'blendShapeDefinition',
                            'isSymetrical' : True,
                            'control' : 'Character_LF_EyeLidShapes00_ctr_facialRig',
                            'blendShapes':{
                                        "UpLidDn"           : {"connection": "UpLidUD"         ,"value":  10},
                                        "UpLidDnHalf"       : {"connection": "UpLidUD"         ,"value":   5},
                                        "UpLidUp"           : {"connection": "UpLidUD"         ,"value": -10},
                                        "LowLidUp"          : {"connection": "LowLidUD"        ,"value":  10},
                                        "LowLidUpHalf"      : {"connection": "LowLidUD"        ,"value":   5},
                                        "LowLidDn"          : {"connection": "LowLidUD"        ,"value": -10},
                                        "UpperEyeLidSpinCW" : {"connection": "UpLidSpin"       ,"value":  10},
                                        "UpperEyeLidSpinCCW": {"connection": "UpLidSpin"       ,"value": -10},
                                        "LowerEyeLidSpinCW" : {"connection": "LowLidSpin"      ,"value":  10},
                                        "LowerEyeLidSpinCCW": {"connection": "LowLidSpin"      ,"value": -10},
                                        #"EyeSpinCCW"       : {"connection": "Spin"            ,"value":  10},
                                        #"EyeSpinCW"        : {"connection": "Spin"            ,"value": -10},
                                        "Bulge"             : {"connection": "Bulge"           ,"value":  10},
                                        "UpperSquint"       : {"connection": "UpperSquint"     ,"value":  10},
                                        "LowerSquint"       : {"connection": "LowerSquint"     ,"value":  10},
                                        "UpLidInnerUp"      : {"connection": "UpLidInnerUD"    ,"value":  10},
                                        "UpLidInnerDn"      : {"connection": "UpLidInnerUD"    ,"value": -10},
                                        "UpLidMidUp"        : {"connection": "UpLidMidUD"      ,"value":  10},
                                        "UpLidMidDown"      : {"connection": "UpLidMidUD"      ,"value": -10},
                                        "UpLidOuterUp"      : {"connection": "UpLidOuterUD"    ,"value":  10},
                                        "UpLidOuterDown"    : {"connection": "UpLidOuterUD"    ,"value": -10},

                                        "LowLidInnerUp"     : {"connection": "LowLidInnerUD"   ,"value":  10},
                                        "LowLidInnerDown"   : {"connection": "LowLidInnerUD"   ,"value": -10},
                                        "LowLidMidUp"       : {"connection": "LowLidMidUD"     ,"value":  10},
                                        "LowLidMidDown"     : {"connection": "LowLidMidUD"     ,"value": -10},
                                        "LowLidOuterUp"     : {"connection": "LowLidOuterUD"   ,"value":  10},
                                        "LowLidOuterDown"   : {"connection": "LowLidOuterUD"   ,"value": -10},
                                        
                                        "CornerInnerUp"     : {"connection": "CornerOuterUD"   ,"value":  10},
                                        "CornerOuterUp"     : {"connection": "CornerOuterUD"   ,"value":  10}},
                            "attributes" : {
                                             'UpLidUD'       :{"type": "float", "min": -10, "max":10},
                                             'LowLidUD'      :{"type": "float", "min": -10, "max":10},
                                             'UpLidSpin'     :{"type": "float", "min": -10, "max":10}, 
                                             'LowLidSpin'    :{"type": "float", "min": -10, "max":10},
                                             'Spin'          :{"type": "float", "min": -10, "max":10},
                                             'UpLidInOut'    :{"type": "float", "min": -10, "max":10},
                                             'LowLidInOut'   :{"type": "float", "min": -10, "max":10},
                                             'Bulge'         :{"type": "float", "min":   0, "max":10}, 
                                             'UpperSquint'   :{"type": "float", "min":   0, "max":10}, 
                                             'LowerSquint'   :{"type": "float", "min":   0, "max":10},
                                             'UpLidInnerUD'  :{"type": "float", "min": -10, "max":10}, 
                                             'UpLidMidUD'    :{"type": "float", "min": -10, "max":10}, 
                                             'UpLidOuterUD'  :{"type": "float", "min": -10, "max":10}, 
                                             'LowLidInnerUD' :{"type": "float", "min": -10, "max":10}, 
                                             'LowLidMidUD'   :{"type": "float", "min": -10, "max":10}, 
                                             'LowLidOuterUD' :{"type": "float", "min": -10, "max":10}, 
                                             'CornerInnerUD' :{"type": "float", "min":   0, "max":10}, 
                                             'CornerOuterUD' :{"type": "float", "min":   0, "max":10}},

                            'order':    ['UpLidUD','LowLidUD','UpLidSpin','LowLidSpin','Spin','UpLidInOut','LowLidInOut',
                                         'Bulge','UpperSquint','LowerSquint','UpLidInnerUD','UpLidMidUD',
                                         'UpLidOuterUD','LowLidInnerUD','LowLidMidUD' ,'LowLidOuterUD','CornerInnerUD',
                                         'CornerOuterUD']
                            }}
EyeBallPupil = {"EyeBall":{'Type'         : 'blendShapeDefinition',
                           'baseMesh'     : 'LEyeBall',
                           'isSymetrical' : True,
                           'control'      : 'Character_LF_EyeLidShapes00_ctr_facialRig',
                           'blendShapes'  : {'irisContract'      : {"connection":"Iris",   "value": -10},
                                            'irisExpand'         : {"connection":"Iris",   "value":  10},
                                            'PupilContract'      : {"connection":"Pupil",  "value": -10},
                                            'PupilExpand'        : {"connection":"Pupil",  "value":  10}},
                           'attributes'   : {'Iris'         : {"type": "float", "min":-10, "max":10},
                                             'Pupil'         : {"type": "float", "min":-10, "max":10}},            
                           'order'        : ['Iris','Pupil']}}

Cristaline = {"Diverge":{
                            'Type':"blendShapeDefinition",
                            "isSymetrical":True,
                            "baseMesh"    : 'Crystalline',

                            "control"     : "Character_LF_EyeLidShapes00_ctr_facialRig",

                            "attributes"  : {'PupilDivergeUD':{"type": "float", "min":-10, "max":10},
                                             'PupilDivergeLR':{"type": "float", "min":-10, "max":10}},

                            "blendShapes" : {  'PupilDivergeUp'      : {"connection":"PupilDivergeUD"  ,"value":  10},
                                               'PupilDivergeDn'      : {"connection":"PupilDivergeUD"  ,"value": -10},
                                               'PupilDivergeLf'      : {"connection":"PupilDivergeLR"  ,"value":  10},
                                               'PupilDivergeRh'      : {"connection":"PupilDivergeLR"  ,"value": -10}},
                            'order'       : ['PupilDivergeUD' , 'PupilDivergeLR']}}
mouthSecondarys = { "lipUpperMidSecondary":{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_RH_MidUpLip00_ctr_facialRig",
                                "attributes"  :{"UD"     :{"type": "float", "min":-10, "max":10},
                                                "FB"     :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'UpperMidUp' : {"connection":"UD"  ,"value":  10},
                                                'UpperMidDn' : {"connection":"UD"  ,"value": -10},
                                                'UpperMidFn' : {"connection":"FB"  ,"value":  10},
                                                'UpperMidBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']},
                    "lipLowMidSecondary" :{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_RH_MidLowLip00_ctr_facialRig",
                                "attributes"  :{"UD"     :{"type": "float", "min":-10, "max":10},
                                                "FB"     :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'LowMidUp' : {"connection":"UD"  ,"value":  10},
                                                'LowMidDn' : {"connection":"UD"  ,"value": -10},
                                                'LowMidFn' : {"connection":"FB"  ,"value":  10},
                                                'LowMidBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']},
                    "LipCornerSecondary" :{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_RH_CornerLip00_ctr_facialRig",
                                "attributes"  :{"UD"       : {"type": "float", "min":-10, "max":10},
                                                "FB"       : {"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'CornerUp' : {"connection":"UD"  ,"value":  10},
                                                'CornerDn' : {"connection":"UD"  ,"value": -10},
                                                'CornerFn' : {"connection":"FB"  ,"value":  10},
                                                'CornerBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']},
                    "LipUpperSecondary" :{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":False,
                                "baseMesh"    : "Character",
                                "control"     : "Character_MD_MidLowLip00_ctr_facialRig",
                                "attributes"  :{"UD"     :{"type": "float", "min":-10, "max":10},
                                                "FB"     :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'LowUp' : {"connection":"UD"  ,"value":  10},
                                                'LowDn' : {"connection":"UD"  ,"value": -10},
                                                'LowFn' : {"connection":"FB"  ,"value":  10},
                                                'LowBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']},
                    "LipLowSecondary" :{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":False,
                                "baseMesh"    : "Character",
                                "control"     : "Character_MD_MidUpLip00_ctr_facialRig",
                                "attributes"  :{"UD"     :{"type": "float", "min":-10, "max":10},
                                                "FB"     :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{'UpperUp' : {"connection":"UD"  ,"value":  10},
                                                'UpperDn' : {"connection":"UD"  ,"value": -10},
                                                'UpperFn' : {"connection":"FB"  ,"value":  10},
                                                'UpperBk' : {"connection":"FB"  ,"value": -10}},
                                'order'       :['UD' , 'FB']}}
EyeJawJoints = {"lidJoints":{
                    'Type'        : "jointLinkDefinition",
                    'isSymetrical': True,
                    'control'     :  'Character_LF_EyeLidShapes00_ctr_facialRig',
                    'joints'      : {'Character_LF_EyeUpperLid00_sknjnt_Rig':{"connection":"UpLidUD" , "inputPlug":"rotateY","value" : [[-10, -45] ,[0,0] ,[10, 16]]},
                                     "Character_LF_EyeLowerLid00_sknjnt_Rig":{"connection":"LowLidUD", "inputPlug":"rotateY","value" : [[-10,  16] ,[0,0] ,[10,-45]]},
                                     "Character_LF_EyeLidSpin00_grp_Rig"    :{"connection":"spin"    , "inputPlug":"rotateX","value" : [[-10, -45] ,[0,0] ,[10,45]]}},
                    "attributes"  : {"UpLidUD"      :{"type": "float", "min":-10, "max":10},
                                     "LowLidUD"     :{"type": "float", "min":-10, "max":10},
                                     "spin"         :{"type": "float", "min":-10, "max":10}},
                    'order'       : ['UpLidUD' , 'LowLidUD', 'spin']},
                "jawjoint":{
                    'Type'        : "jointLinkDefinition",
                    'isSymetrical': False,
                    'control'     : 'Character_MD_Jaw00_ctr_rig',
                    'joints'      : {"Character_MD_Jaw_sknjnt_RIG":{"connection":"rotateZ" , "inputPlug":"rotateZ", "value" : None}},
                    'attributes'  : {'rotateZ':{}},
                    'order'       : ['rotateZ']}
                }

mouth = { "mouthMain":{
                    'Type'        : "blendShapeDefinition",
                    'isSymetrical': False,
                    'control'     :  'Character_LF_EyeLidShapes00_ctr_facialRig',
                    'blendShapes' :{'Smile'         : {"connection":"SmileFrown"    ,"value":  10},
                                     'Frown'        : {"connection":"SmileFrown"    ,"value": -10},
                                     'Wide'         : {"connection":"NarrowWide"    ,"value":  10},
                                     'Narrow'       : {"connection":"NarrowWide"    ,"value": -10},
                                     'Ooo'          : {"connection":"Ooo"           ,"value":  10},
                                     'CornerUp'     : {"connection":"CornerUD"      ,"value":  10},
                                     'CornerDn'     : {"connection":"CornerUD"      ,"value": -10},
                                     'Pinch'        : {"connection":"Pinch"         ,"value":  10},
                                     'LSmile'       : {"connection":"SmileFrownL"   ,"value":  10},
                                     'LFrown'       : {"connection":"SmileFrownL"   ,"value": -10},
                                     'RSmile'       : {"connection":"SmileFrownR"   ,"value":  10},
                                     'RFrown'       : {"connection":"SmileFrownR"   ,"value": -10},
                                     'LWide'        : {"connection":"NarrowWideL"   ,"value":  10},
                                     'LNarrow'      : {"connection":"NarrowWideL"   ,"value": -10},
                                     'RWide'        : {"connection":"NarrowWideR"   ,"value":  10},
                                     'RNarrow'      : {"connection":"NarrowWideR"   ,"value": -10},
                                     'LCornerUp'    : {"connection":"CornerL"       ,"value":  10},
                                     'LCornerDn'    : {"connection":"CornerL"       ,"value": -10},
                                     'RCornerUp'    : {"connection":"CornerR"       ,"value":  10},
                                     'RCornerDn'    : {"connection":"CornerR"       ,"value": -10},
                                     'Lpinch'       : {"connection":"PinchL"        ,"value":  10},
                                     'Rpinch'       : {"connection":"PinchR"        ,"value":  10},
                                     'LUpperSneer'  : {"connection":"UpperLipSneerL","value":  10},
                                     'RUpperSneer'  : {"connection":"UpperLipSneerR","value":  10},
                                     'MUpperSneerUp': {"connection":"UpperLipMidUD" ,"value":  10},
                                     'MUpperSneerDn': {"connection":"UpperLipMidUD" ,"value": -10},
                                     'LLowSneer'    : {"connection":"LowerLipSneerL","value":  10},
                                     'RLowSneer'    : {"connection":"LowerLipSneerR","value":  10},
                                     'MLowSneerUp'  : {"connection":"LowerLipSneerUD","value": -10},
                                     'MLowSneerDn'  : {"connection":"LowerLipSneerUD","value":  10}},
                    'attributes'  :{'SmileFrown'     :{"type": "float", "min":-10, "max":10}, 
                                    'NarrowWide'     :{"type": "float", "min":-10, "max":10},
                                    'Ooo'            :{"type": "float", "min":  0, "max":10},
                                    #'Press'          :{"type": "float", "min":  0, "max":10}, 
                                    #'Puff'           :{"type": "float", "min":  0, "max":10},
                                    'CornerUD'       :{"type": "float", "min":-10, "max":10},
                                    'Pinch'          :{"type": "float", "min":  0, "max":10},
                                    'LeftRightShapes':{"type": "float", "min":  0, "max":10, "keyable" : False },
                                    'SmileFrownL'    :{"type": "float", "min":-10, "max":10}, 
                                    'SmileFrownR'    :{"type": "float", "min":-10, "max":10}, 
                                    'NarrowWideL'    :{"type": "float", "min":-10, "max":10}, 
                                    'NarrowWideR'    :{"type": "float", "min":-10, "max":10}, 
                                    'CornerL'        :{"type": "float", "min":-10, "max":10}, 
                                    'CornerR'        :{"type": "float", "min":-10, "max":10}, 
                                    'PinchL'         :{"type": "float", "min":  0, "max":10},
                                    'PinchR'         :{"type": "float", "min":  0, "max":10},
                                    'UpperLip'       :{"type": "float", "min":  0, "max":10, "keyable" : False },
                                    'UpperLipSneerL' :{"type": "float", "min":  0, "max":10},
                                    'UpperLipSneerR' :{"type": "float", "min":  0, "max":10},
                                    'UpperLipMidUD'  :{"type": "float", "min":-10, "max":10}, 
                                    'LowerLip'       :{"type": "float", "min":  0, "max":10, "keyable" : False },
                                    'LowerLipSneerL' :{"type": "float", "min":  0, "max":10},
                                    'LowerLipSneerR' :{"type": "float", "min":  0, "max":10},
                                    'LowerLipMidUD'  :{"type": "float", "min":-10, "max":10}, 
                                    'Jaw'            :{"type": "float", "min":  0, "max":10, "keyable" : False },
                                    'StickyLips'     :{"type": "float", "min":  0, "max":10}},
                      'order'     :['SmileFrown','NarrowWide','Ooo','Press','Puff','CornerUD','Pinch','LeftRightShapes',
                                    'SmileFrownL','SmileFrownR','NarrowWideL','NarrowWideR','CornerL','CornerR','PinchL',
                                    'CornerR','PinchL','PinchR','UpperLip','UpperLipSneerL','UpperLipSneerR','UpperLipMidUD',
                                    'UpperLipMidUD','LowerLip','LowerLipSneerL','LowerLipSneerR','LowerLipMidUD','Jaw','StickyLips']}
}

Cheeks = {'cheeks' :{'Type'        : "blendShapeDefinition",
                     'isSymetrical': True,
                     'control'     :  'Character_LF_EyeLidShapes00_ctr_facialRig',
                     'blendShapes' :{'cheekUp'   : {"connection":"UD"    ,"value":  10},
                                     'cheekDn'   : {"connection":"UD"    ,"value": -10},
                                     'cheekIn'   : {"connection":"LR"    ,"value":  10},
                                     'cheekOut'  : {"connection":"LR"    ,"value": -10},
                                     'cheekFn'   : {"connection":"FB"    ,"value": -10},
                                     'cheekBk'   : {"connection":"FB"    ,"value": -10},
                                     'Squint'    : {"connection":"Squint","value":  10},
                                     'PuffOut'   : {"connection":"PUFF"  ,"value":  10},
                                     'PuffIn'    : {"connection":"PUFF"  ,"value": -10}},

                     'attributes'  :{"UD"         :{"type": "float", "min":-10, "max":10},
                                     "LR"         :{"type": "float", "min":-10, "max":10},
                                     "FB"         :{"type": "float", "min":-10, "max":10},
                                     "Squint"     :{"type": "float", "min":  0, "max":10},
                                     "PUFF"       :{"type": "float", "min":-10, "max":10}},
                      'order'      :["UD","LR","FB","Squint","PUFF"]}}
mouthMover = {'mouthMover'  : {'Type'        : "blendShapeDefinition",
                     'isSymetrical': False,
                     'control'     :  'Character_LF_EyeLidShapes00_ctr_facialRig',
                     'blendShapes' :{'mouthUp'        :{"connection":"UD"            ,"value":   10},
                                     'mouthDn'        :{"connection":"UD"            ,"value":  -10},
                                     'mouthLf'        :{"connection":"LR"            ,"value":   10},
                                     'mouthRh'        :{"connection":"LR"            ,"value":  -10},
                                     'mouthFn'        :{"connection":"FB"            ,"value":   10},
                                     'mouthBk'        :{"connection":"FB"            ,"value":  -10},
                                     'TiltCw'         :{"connection":"Tilt"          ,"value":   10},
                                     'TiltCcw'        :{"connection":"Tilt"          ,"value":  -10},
                                     'UpperLipUp'     :{"connection":"UpperLipUD"    ,"value":   10},
                                     'UpperLipDn'     :{"connection":"UpperLipUD"    ,"value":  -10},
                                     'UpperLipFn'     :{"connection":"UpperLipFB"    ,"value":   10},
                                     'UpperLipBk'     :{"connection":"UpperLipFB"    ,"value":  -10},
                                     'UpperLipCw'     :{"connection":"UpperLipTILT"  ,"value":   10},
                                     'UpperLipCcw'    :{"connection":"UpperLipTILT"  ,"value":  -10},
                                     'UpperLipCurlIn' :{"connection":"UpperLipCurl"  ,"value":   10},
                                     'UpperLipCurlOut':{"connection":"UpperLipCurl"  ,"value":  -10},
                                     'LowLipUp'       :{"connection":"LowerLipUD"    ,"value":   10},
                                     'LowLipDn'       :{"connection":"LowerLipUD"    ,"value":  -10},
                                     'LowLipFn'       :{"connection":"LowerLipFB"    ,"value":   10},
                                     'LowLipBk'       :{"connection":"LowerLipFB"    ,"value":  -10},
                                     'LowLipCw'       :{"connection":"LowerLipTILT"  ,"value":   10},
                                     'LowLipCcw'      :{"connection":"LowerLipTILT"  ,"value":  -10},
                                     'LowLipCurlIn'   :{"connection":"LowLipCurl"    ,"value":   10},
                                     'LowLipCurlOut'  :{"connection":"LowerLipCurl"  ,"value":  -10}},
                     'attributes'  :{ 'UD'            :{"type": "float", "min":-10, "max":10}, 
                                      'LR'            :{"type": "float", "min":-10, "max":10}, 
                                      'FB'            :{"type": "float", "min":-10, "max":10}, 
                                      'TILT'          :{"type": "float", "min":-10, "max":10},
                                      'Upper_Lip'     :{"type": "float", "min":-10, "max":10 , "keyable" : False},
                                      'UpperLipUD'    :{"type": "float", "min":-10, "max":10},
                                      'UpperLipFB'    :{"type": "float", "min":-10, "max":10},
                                      'UpperLipTILT'  :{"type": "float", "min":-10, "max":10},
                                      'UpperLipCurl'  :{"type": "float", "min":-10, "max":10},
                                      'Lower_Lip'     :{"type": "float", "min":-10, "max":10 , "keyable" : False},
                                      'LowerLipUD'    :{"type": "float", "min":-10, "max":10},
                                      'LowerLipFB'    :{"type": "float", "min":-10, "max":10},
                                      'LowerLipTILT'  :{"type": "float", "min":-10, "max":10},
                                      'LowerLipCurl'  :{"type": "float", "min":-10, "max":10}},
                      'order'      :["UD","LR","FB","TILT","Upper_Lip","UpperLipUD","UpperLipFB",
                                     "UpperLipTILT","UpperLipCurl","Lower_Lip","LowerLipUD",
                                     "LowerLipFB","LowerLipTILT","LowerLipCurl"]}}


Nose = {'Nose':       {'Type'        : "blendShapeDefinition",
                        'isSymetrical': False,
                        'control'     :  'Character_MD_Nose00_ctr_facialRig',
                        'blendShapes' :{'noseUp'         :{"connection":"UD"                ,"value":   10},
                                        'noseDn'         :{"connection":"UD"                ,"value":  -10},
                                        'noseLf'         :{"connection":"LR"                ,"value":   10},
                                        'noseRh'         :{"connection":"LR"                ,"value":  -10},
                                        'noseFn'         :{"connection":"FB"                ,"value":   10},
                                        'noseBk'         :{"connection":"FB"                ,"value":  -10},
                                        'noseCurlUp'     :{"connection":"Curl"              ,"value":   10},
                                        'noseCurlDn'     :{"connection":"Curl"              ,"value":  -10},
                                        'noseTiltCw'     :{"connection":"Tilt"              ,"value":   10},
                                        'noseTiltCcw'    :{"connection":"Tilt"              ,"value":  -10},
                                        'noseLSneer'     :{"connection":"LSneer"            ,"value":   10},
                                        'noseRSneer'     :{"connection":"RSneer"            ,"value":   10},
                                        'noseLFlareIn'   :{"connection":"LFlare"            ,"value":  -10},
                                        'noseLFlareOut'  :{"connection":"LFlare"            ,"value":   10},
                                        'noseRFlareIn'   :{"connection":"RFlare"            ,"value":  -10},
                                        'noseRFlareOut'  :{"connection":"RFlare"            ,"value":   10}
                                       },

                        'attributes' :{
                            "UD"     :{"type": "float", "min":-10, "max":10},
                            "LR"     :{"type": "float", "min":-10, "max":10},
                            "FB"     :{"type": "float", "min":-10, "max":10},
                            "Curl"   :{"type": "float", "min":-10, "max":10},
                            "Tilt"   :{"type": "float", "min":-10, "max":10},
                            "LSneer" :{"type": "float", "min":  0, "max":10},
                            "RSneer" :{"type": "float", "min":  0, "max":10},
                            "LFlare" :{"type": "float", "min":-10, "max":10},
                            "RFlare" :{"type": "float", "min":-10, "max":10}
                            },
                        'order'      :["UD","LR","FB","Curl","Tilt","LSneer","RSneer",
                                     "UpperLipTILT","UpperLipCurl","Lower_Lip","LowerLipUD",
                                     "LFlare","RFlare"]}}


Furrow = {'Furrow':    {'Type'        : "blendShapeDefinition",
                        'isSymetrical': False,
                        'control'     :  'Character_MD_Furrow00_ctr_facialRig',
                        'blendShapes' :{'Furrow'         :{"connection":"Furrow"        ,"value":   10},
                                        'FurrowUp'       :{"connection":"UD"            ,"value":   10},
                                        'FurrowDn'       :{"connection":"UD"            ,"value":  -10},
                                        'FurrowFn'       :{"connection":"FB"            ,"value":   10},
                                        'FurrowBk'       :{"connection":"FB"            ,"value":  -10},
                                        'FurrowLf'       :{"connection":"LR"            ,"value":   10},
                                        'FurrowRh'       :{"connection":"LR"            ,"value":  -10},
                                        'FurrowTiltCw'   :{"connection":"TILT"          ,"value":   10},
                                        'FurrowTiltCcw'  :{"connection":"TILT"          ,"value":  -10},
                                        'FurrowL'        :{"connection":"FurrowL"       ,"value":   10},
                                        'FurrowR'        :{"connection":"FurrowR"       ,"value":   10}
                                        },
                        'attributes' : {
                            'Furrow'           :{"type": "float", "min":  0, "max":10},
                            'UD'               :{"type": "float", "min":-10, "max":10},
                            'FB'               :{"type": "float", "min":-10, "max":10},
                            'LR'               :{"type": "float", "min":-10, "max":10},
                            'TILT'             :{"type": "float", "min":-10, "max":10},
                            'Left_Right_Shapes':{"type": "float", "min":-10, "max":10 , "keyable":False},
                            'FurrowL'          :{"type": "float", "min":  0, "max":10},
                            'FurrowR'          :{"type": "float", "min":  0, "max":10}
                            },
                        'order'      :['Furrow',"UD","LR","FB","TILT","Left_Right_Shapes","FurrowL","FurrowR"]}}


secondaryEyeBrow = {
                    "EyeBrowMidSecondary":{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_LF_InnerEyeBrow00_ctr_facialRig",
                                "attributes"  :{"UD"   :{"type": "float", "min":-10, "max":10},
                                                "LR"   :{"type": "float", "min":-10, "max":10},
                                                "FB"   :{"type": "float", "min":-10, "max":10},
                                                "Tilt" :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{
                                                'BrowMidUp'      : {"connection":"UD"  ,"value":  10},
                                                'BrowMidDn'      : {"connection":"UD"  ,"value": -10},
                                                'BrowMidLf'      : {"connection":"LR"  ,"value":  10},
                                                'BrowMidRh'      : {"connection":"LR"  ,"value": -10},
                                                'BrowMidFn'      : {"connection":"FB"  ,"value":  10},
                                                'BrowMidBk'      : {"connection":"FB"  ,"value": -10},
                                                'BrowMidTiltCw'  : {"connection":"Tilt","value":  10},
                                                'BrowMidTiltCcw' : {"connection":"Tilt","value": -10},
                                                },
                                'order'       :['UD' , 'LR' ,'FB','Tilt']},
                    "EyeBrowInnerSecondary":{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_LF_InnerEyeBrow00_ctr_facialRig",
                                "attributes"  :{"UD"   :{"type": "float", "min":-10, "max":10},
                                                "LR"   :{"type": "float", "min":-10, "max":10},
                                                "FB"   :{"type": "float", "min":-10, "max":10},
                                                "Tilt" :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{
                                                'BrowInUp'      : {"connection":"UD"  ,"value":  10},
                                                'BrowInDn'      : {"connection":"UD"  ,"value": -10},
                                                'BrowInLf'      : {"connection":"LR"  ,"value":  10},
                                                'BrowInRh'      : {"connection":"LR"  ,"value": -10},
                                                'BrowInFn'      : {"connection":"FB"  ,"value":  10},
                                                'BrowInBk'      : {"connection":"FB"  ,"value": -10},
                                                'BrowInTiltCw'  : {"connection":"Tilt","value":  10},
                                                'BrowInTiltCcw' : {"connection":"Tilt","value": -10},
                                                },
                                'order'       :['UD' , 'LR' ,'FB','Tilt']},
                    "EyeBrowOutSecondary":{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_LF_InnerEyeBrow00_ctr_facialRig",
                                "attributes"  :{"UD"   :{"type": "float", "min":-10, "max":10},
                                                "LR"   :{"type": "float", "min":-10, "max":10},
                                                "FB"   :{"type": "float", "min":-10, "max":10},
                                                "Tilt" :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{
                                                'BrowOutUp'   : {"connection":"UD"  ,"value":  10},
                                                'BrowOutDn'   : {"connection":"UD"  ,"value": -10},
                                                'BrowOutLf'   : {"connection":"LR"  ,"value":  10},
                                                'BrowOutRh'  : {"connection":"LR"  ,"value": -10},
                                                'BrowOutFn'   : {"connection":"FB"  ,"value":  10},
                                                'BrowOutBk'   : {"connection":"FB"  ,"value": -10},
                                                'BrowOutTiltCw' : {"connection":"Tilt","value":  10},
                                                'BrowOutTiltCcw' : {"connection":"Tilt","value": -10},
                                                },
                                'order'       :['UD' , 'LR' ,'FB','Tilt']}
                }
EyeBrow ={ "EyeBrow":{
                                'Type' : "blendShapeDefinition",
                                "isSymetrical":True,
                                "baseMesh"    : "Character",
                                "control"     : "Character_LF_EyeBrow00_ctr_facialRig",
                                "attributes"  :{"Angry"   :{"type": "float", "min":0, "max":10},
                                                "Sad"     :{"type": "float", "min":0, "max":10},
                                                "Surprise":{"type": "float", "min":0, "max":10},
                                                "UD"      :{"type": "float", "min":-10, "max":10},
                                                "LR"      :{"type": "float", "min":-10, "max":10},
                                                "FB"      :{"type": "float", "min":-10, "max":10},
                                                "Tilt"    :{"type": "float", "min":-10, "max":10}},
                                "blendShapes" :{
                                                'Angry'    : {"connection":"Angry"     ,"value":  10},
                                                'Sad'      : {"connection":"Sad"       ,"value":  10},
                                                'Surprise' : {"connection":"Surprise"  ,"value":  10},

                                                'BrowUp'   : {"connection":"UD"  ,"value":  10},
                                                'BrowDn'   : {"connection":"UD"  ,"value": -10},
                                                'BrowIn'   : {"connection":"LR"  ,"value":  10},
                                                'BrowOut'  : {"connection":"LR"  ,"value": -10},
                                                'BrowFn'   : {"connection":"FB"  ,"value":  10},
                                                'BrowTiltCw' : {"connection":"Tilt","value":  10},
                                                'BrowTiltCcw' : {"connection":"Tilt","value": -10},
                                                },
                                'order'       :['UD' , 'LR' ,'FB','Tilt']}
          }
