# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_RigTools.ui'
#
# Created: Wed Nov 01 23:16:45 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(485, 669)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.MiscGroupBox = QtWidgets.QGroupBox(Form)
        self.MiscGroupBox.setObjectName("MiscGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MiscGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RenameTool = QtWidgets.QPushButton(self.MiscGroupBox)
        self.RenameTool.setObjectName("RenameTool")
        self.verticalLayout_4.addWidget(self.RenameTool)
        self.ExtractGeoBtn = QtWidgets.QPushButton(self.MiscGroupBox)
        self.ExtractGeoBtn.setObjectName("ExtractGeoBtn")
        self.verticalLayout_4.addWidget(self.ExtractGeoBtn)
        self.ParentConstraintBtn = QtWidgets.QPushButton(self.MiscGroupBox)
        self.ParentConstraintBtn.setObjectName("ParentConstraintBtn")
        self.verticalLayout_4.addWidget(self.ParentConstraintBtn)
        self.AttributeTransferBtn = QtWidgets.QPushButton(self.MiscGroupBox)
        self.AttributeTransferBtn.setToolTip("")
        self.AttributeTransferBtn.setObjectName("AttributeTransferBtn")
        self.verticalLayout_4.addWidget(self.AttributeTransferBtn)
        self.verticalLayout_17.addWidget(self.MiscGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_17)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ConstShapeLblBtn = QtWidgets.QPushButton(self.groupBox)
        self.ConstShapeLblBtn.setObjectName("ConstShapeLblBtn")
        self.verticalLayout_9.addWidget(self.ConstShapeLblBtn)
        self.SCCombineButton = QtWidgets.QPushButton(self.groupBox)
        self.SCCombineButton.setObjectName("SCCombineButton")
        self.verticalLayout_9.addWidget(self.SCCombineButton)
        self.CopyCvsPosBtn = QtWidgets.QPushButton(self.groupBox)
        self.CopyCvsPosBtn.setObjectName("CopyCvsPosBtn")
        self.verticalLayout_9.addWidget(self.CopyCvsPosBtn)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.AlignGroupBox = QtWidgets.QGroupBox(Form)
        self.AlignGroupBox.setObjectName("AlignGroupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.AlignGroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.AlignRotation = QtWidgets.QPushButton(self.AlignGroupBox)
        self.AlignRotation.setObjectName("AlignRotation")
        self.verticalLayout_10.addWidget(self.AlignRotation)
        self.AlignPosition = QtWidgets.QPushButton(self.AlignGroupBox)
        self.AlignPosition.setObjectName("AlignPosition")
        self.verticalLayout_10.addWidget(self.AlignPosition)
        self.AlignAll = QtWidgets.QPushButton(self.AlignGroupBox)
        self.AlignAll.setObjectName("AlignAll")
        self.verticalLayout_10.addWidget(self.AlignAll)
        self.verticalLayout_11.addWidget(self.AlignGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.GroupsGroupBox = QtWidgets.QGroupBox(Form)
        self.GroupsGroupBox.setObjectName("GroupsGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.GroupsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CreateChildGroup = QtWidgets.QPushButton(self.GroupsGroupBox)
        self.CreateChildGroup.setObjectName("CreateChildGroup")
        self.verticalLayout.addWidget(self.CreateChildGroup)
        self.groupBox_2 = QtWidgets.QGroupBox(self.GroupsGroupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.worldRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.worldRadio.setObjectName("worldRadio")
        self.horizontalLayout_8.addWidget(self.worldRadio)
        self.parentRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.parentRadio.setObjectName("parentRadio")
        self.horizontalLayout_8.addWidget(self.parentRadio)
        self.insertedRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.insertedRadio.setChecked(True)
        self.insertedRadio.setObjectName("insertedRadio")
        self.horizontalLayout_8.addWidget(self.insertedRadio)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.CreateParentGroup = QtWidgets.QPushButton(self.groupBox_2)
        self.CreateParentGroup.setObjectName("CreateParentGroup")
        self.verticalLayout_7.addWidget(self.CreateParentGroup)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.JointsGroupBox = QtWidgets.QGroupBox(self.GroupsGroupBox)
        self.JointsGroupBox.setObjectName("JointsGroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.JointsGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.JointsOnPoints = QtWidgets.QPushButton(self.JointsGroupBox)
        self.JointsOnPoints.setObjectName("JointsOnPoints")
        self.verticalLayout_8.addWidget(self.JointsOnPoints)
        self.OrientNubButton = QtWidgets.QPushButton(self.JointsGroupBox)
        self.OrientNubButton.setObjectName("OrientNubButton")
        self.verticalLayout_8.addWidget(self.OrientNubButton)
        self.verticalLayout.addWidget(self.JointsGroupBox)
        self.horizontalLayout.addWidget(self.GroupsGroupBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RigGroupBox = QtWidgets.QGroupBox(Form)
        self.RigGroupBox.setObjectName("RigGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.RigGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FKOnSelection = QtWidgets.QPushButton(self.RigGroupBox)
        self.FKOnSelection.setObjectName("FKOnSelection")
        self.verticalLayout_2.addWidget(self.FKOnSelection)
        self.IKOnSelection = QtWidgets.QPushButton(self.RigGroupBox)
        self.IKOnSelection.setObjectName("IKOnSelection")
        self.verticalLayout_2.addWidget(self.IKOnSelection)
        self.GenericJointChainRigBtn = QtWidgets.QPushButton(self.RigGroupBox)
        self.GenericJointChainRigBtn.setObjectName("GenericJointChainRigBtn")
        self.verticalLayout_2.addWidget(self.GenericJointChainRigBtn)
        self.groupBox_3 = QtWidgets.QGroupBox(self.RigGroupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.MainProgresiveLayout = QtWidgets.QVBoxLayout()
        self.MainProgresiveLayout.setObjectName("MainProgresiveLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.MainProgresiveLayout.addWidget(self.label)
        self.ProgressiveDepthSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.ProgressiveDepthSpinBox.setMinimum(1)
        self.ProgressiveDepthSpinBox.setProperty("value", 1)
        self.ProgressiveDepthSpinBox.setObjectName("ProgressiveDepthSpinBox")
        self.MainProgresiveLayout.addWidget(self.ProgressiveDepthSpinBox)
        self.ProgressiveConstraintButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ProgressiveConstraintButton.setObjectName("ProgressiveConstraintButton")
        self.MainProgresiveLayout.addWidget(self.ProgressiveConstraintButton)
        self.mantainOffsetChk = QtWidgets.QCheckBox(self.groupBox_3)
        self.mantainOffsetChk.setChecked(True)
        self.mantainOffsetChk.setObjectName("mantainOffsetChk")
        self.MainProgresiveLayout.addWidget(self.mantainOffsetChk)
        self.horizontalLayout_5.addLayout(self.MainProgresiveLayout)
        self.ProgressiveTypeLayout = QtWidgets.QVBoxLayout()
        self.ProgressiveTypeLayout.setObjectName("ProgressiveTypeLayout")
        self.CnstParentRadio = QtWidgets.QRadioButton(self.groupBox_3)
        self.CnstParentRadio.setObjectName("CnstParentRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstParentRadio)
        self.CnstOrientRadio = QtWidgets.QRadioButton(self.groupBox_3)
        self.CnstOrientRadio.setChecked(True)
        self.CnstOrientRadio.setObjectName("CnstOrientRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstOrientRadio)
        self.CnstPointRadio = QtWidgets.QRadioButton(self.groupBox_3)
        self.CnstPointRadio.setObjectName("CnstPointRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstPointRadio)
        self.horizontalLayout_5.addLayout(self.ProgressiveTypeLayout)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.unfoldRigGrpBox = QtWidgets.QGroupBox(self.RigGroupBox)
        self.unfoldRigGrpBox.setObjectName("unfoldRigGrpBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.unfoldRigGrpBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.initRadiusLbl = QtWidgets.QLabel(self.unfoldRigGrpBox)
        self.initRadiusLbl.setObjectName("initRadiusLbl")
        self.horizontalLayout_4.addWidget(self.initRadiusLbl)
        self.initRadiusSpnBx = QtWidgets.QDoubleSpinBox(self.unfoldRigGrpBox)
        self.initRadiusSpnBx.setObjectName("initRadiusSpnBx")
        self.horizontalLayout_4.addWidget(self.initRadiusSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.endRadiusLbl = QtWidgets.QLabel(self.unfoldRigGrpBox)
        self.endRadiusLbl.setObjectName("endRadiusLbl")
        self.horizontalLayout_6.addWidget(self.endRadiusLbl)
        self.endRadiusSpnBx = QtWidgets.QDoubleSpinBox(self.unfoldRigGrpBox)
        self.endRadiusSpnBx.setObjectName("endRadiusSpnBx")
        self.horizontalLayout_6.addWidget(self.endRadiusSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.numberOfPointsLbl = QtWidgets.QLabel(self.unfoldRigGrpBox)
        self.numberOfPointsLbl.setObjectName("numberOfPointsLbl")
        self.horizontalLayout_7.addWidget(self.numberOfPointsLbl)
        self.NumberOfPointsSpnBx = QtWidgets.QSpinBox(self.unfoldRigGrpBox)
        self.NumberOfPointsSpnBx.setObjectName("NumberOfPointsSpnBx")
        self.horizontalLayout_7.addWidget(self.NumberOfPointsSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.unfoldRigBtn = QtWidgets.QPushButton(self.unfoldRigGrpBox)
        self.unfoldRigBtn.setObjectName("unfoldRigBtn")
        self.verticalLayout_12.addWidget(self.unfoldRigBtn)
        self.verticalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_2.addWidget(self.unfoldRigGrpBox)
        self.horizontalLayout_2.addWidget(self.RigGroupBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.SkiningToolslabel = QtWidgets.QLabel(Form)
        self.SkiningToolslabel.setObjectName("SkiningToolslabel")
        self.verticalLayout_3.addWidget(self.SkiningToolslabel)
        self.ListConnectedJoints = QtWidgets.QPushButton(Form)
        self.ListConnectedJoints.setObjectName("ListConnectedJoints")
        self.verticalLayout_3.addWidget(self.ListConnectedJoints)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.SelectJoints = QtWidgets.QPushButton(Form)
        self.SelectJoints.setObjectName("SelectJoints")
        self.verticalLayout_3.addWidget(self.SelectJoints)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_13.addLayout(self.verticalLayout_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.MiscGroupBox.setTitle(QtWidgets.QApplication.translate("Form", "Misc", None, -1))
        self.RenameTool.setText(QtWidgets.QApplication.translate("Form", "Rename Tool", None, -1))
        self.ExtractGeoBtn.setText(QtWidgets.QApplication.translate("Form", "ExtractGeometry", None, -1))
        self.ParentConstraintBtn.setText(QtWidgets.QApplication.translate("Form", "Parent Constraint", None, -1))
        self.AttributeTransferBtn.setText(QtWidgets.QApplication.translate("Form", "Move Attributes", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Form", "EditShapes", None, -1))
        self.ConstShapeLblBtn.setText(QtWidgets.QApplication.translate("Form", "Const Shape Lbl", None, -1))
        self.SCCombineButton.setText(QtWidgets.QApplication.translate("Form", "Combine", None, -1))
        self.CopyCvsPosBtn.setText(QtWidgets.QApplication.translate("Form", "Copy Cvs Position", None, -1))
        self.AlignGroupBox.setTitle(QtWidgets.QApplication.translate("Form", "Align Tools", None, -1))
        self.AlignRotation.setText(QtWidgets.QApplication.translate("Form", "AlignRotation", None, -1))
        self.AlignPosition.setText(QtWidgets.QApplication.translate("Form", "AlignPosition", None, -1))
        self.AlignAll.setText(QtWidgets.QApplication.translate("Form", "Align Pos & Rot", None, -1))
        self.GroupsGroupBox.setTitle(QtWidgets.QApplication.translate("Form", "Group Creation", None, -1))
        self.CreateChildGroup.setText(QtWidgets.QApplication.translate("Form", "Create Child Group", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "Parent Group", None, -1))
        self.worldRadio.setText(QtWidgets.QApplication.translate("Form", "world", None, -1))
        self.parentRadio.setText(QtWidgets.QApplication.translate("Form", "parent", None, -1))
        self.insertedRadio.setText(QtWidgets.QApplication.translate("Form", "inserted", None, -1))
        self.CreateParentGroup.setText(QtWidgets.QApplication.translate("Form", "Create Parent Group", None, -1))
        self.JointsGroupBox.setTitle(QtWidgets.QApplication.translate("Form", "Joints", None, -1))
        self.JointsOnPoints.setText(QtWidgets.QApplication.translate("Form", "CreateJointsOnPoints", None, -1))
        self.OrientNubButton.setText(QtWidgets.QApplication.translate("Form", "Orient Nub", None, -1))
        self.RigGroupBox.setTitle(QtWidgets.QApplication.translate("Form", "Rig", None, -1))
        self.FKOnSelection.setToolTip(QtWidgets.QApplication.translate("Form", "Select some locators in order to create an FK Control", None, -1))
        self.FKOnSelection.setText(QtWidgets.QApplication.translate("Form", "FK on selection", None, -1))
        self.IKOnSelection.setToolTip(QtWidgets.QApplication.translate("Form", "Select some locators in order to create an FK Control", None, -1))
        self.IKOnSelection.setText(QtWidgets.QApplication.translate("Form", "IK on selection", None, -1))
        self.GenericJointChainRigBtn.setText(QtWidgets.QApplication.translate("Form", "Generic Joint Chain Rig", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("Form", "Progressive Constraint", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Depth", None, -1))
        self.ProgressiveConstraintButton.setText(QtWidgets.QApplication.translate("Form", "Progressive Constraint", None, -1))
        self.mantainOffsetChk.setText(QtWidgets.QApplication.translate("Form", "mantain offset", None, -1))
        self.CnstParentRadio.setText(QtWidgets.QApplication.translate("Form", "parent", None, -1))
        self.CnstOrientRadio.setText(QtWidgets.QApplication.translate("Form", "orient", None, -1))
        self.CnstPointRadio.setText(QtWidgets.QApplication.translate("Form", "point", None, -1))
        self.unfoldRigGrpBox.setTitle(QtWidgets.QApplication.translate("Form", "Unfold Rig", None, -1))
        self.initRadiusLbl.setText(QtWidgets.QApplication.translate("Form", "Init Radius", None, -1))
        self.endRadiusLbl.setText(QtWidgets.QApplication.translate("Form", "End Radius", None, -1))
        self.numberOfPointsLbl.setText(QtWidgets.QApplication.translate("Form", "Number Of Points", None, -1))
        self.unfoldRigBtn.setText(QtWidgets.QApplication.translate("Form", "unfold Rig", None, -1))
        self.SkiningToolslabel.setText(QtWidgets.QApplication.translate("Form", "SkiningTools", None, -1))
        self.ListConnectedJoints.setText(QtWidgets.QApplication.translate("Form", "List Skined Joints", None, -1))
        self.SelectJoints.setText(QtWidgets.QApplication.translate("Form", "Select Joints", None, -1))

