# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Laces.ui'
#
# Created: Wed Mar 21 21:43:33 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(352, 455)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LacesGrpBx = QtWidgets.QGroupBox(Form)
        self.LacesGrpBx.setObjectName("LacesGrpBx")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.LacesGrpBx)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoadShapeBtn = QtWidgets.QPushButton(self.LacesGrpBx)
        self.LoadShapeBtn.setObjectName("LoadShapeBtn")
        self.verticalLayout_2.addWidget(self.LoadShapeBtn)
        self.CurrentShapeLbl = QtWidgets.QLabel(self.LacesGrpBx)
        self.CurrentShapeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentShapeLbl.setObjectName("CurrentShapeLbl")
        self.verticalLayout_2.addWidget(self.CurrentShapeLbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.JointsOnCurve = QtWidgets.QLabel(self.LacesGrpBx)
        self.JointsOnCurve.setObjectName("JointsOnCurve")
        self.horizontalLayout.addWidget(self.JointsOnCurve)
        self.NumberOfJoints = QtWidgets.QSpinBox(self.LacesGrpBx)
        self.NumberOfJoints.setMinimumSize(QtCore.QSize(50, 0))
        self.NumberOfJoints.setMaximumSize(QtCore.QSize(50, 16777215))
        self.NumberOfJoints.setMinimum(2)
        self.NumberOfJoints.setProperty("value", 2)
        self.NumberOfJoints.setObjectName("NumberOfJoints")
        self.horizontalLayout.addWidget(self.NumberOfJoints)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.Mode = QtWidgets.QCheckBox(self.LacesGrpBx)
        self.Mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Mode.setCheckable(True)
        self.Mode.setChecked(False)
        self.Mode.setObjectName("Mode")
        self.verticalLayout_2.addWidget(self.Mode)
        self.CreateControlsBtn = QtWidgets.QPushButton(self.LacesGrpBx)
        self.CreateControlsBtn.setObjectName("CreateControlsBtn")
        self.verticalLayout_2.addWidget(self.CreateControlsBtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.RebuildGrp = QtWidgets.QGroupBox(self.LacesGrpBx)
        self.RebuildGrp.setObjectName("RebuildGrp")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.RebuildGrp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RebuildCurveChk = QtWidgets.QCheckBox(self.RebuildGrp)
        self.RebuildCurveChk.setObjectName("RebuildCurveChk")
        self.verticalLayout.addWidget(self.RebuildCurveChk)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.NumberofSpansLabel = QtWidgets.QLabel(self.RebuildGrp)
        self.NumberofSpansLabel.setObjectName("NumberofSpansLabel")
        self.horizontalLayout_6.addWidget(self.NumberofSpansLabel)
        self.NumberOfSpansSpnBx = QtWidgets.QSpinBox(self.RebuildGrp)
        self.NumberOfSpansSpnBx.setMinimumSize(QtCore.QSize(50, 0))
        self.NumberOfSpansSpnBx.setMaximumSize(QtCore.QSize(50, 16777215))
        self.NumberOfSpansSpnBx.setMinimum(4)
        self.NumberOfSpansSpnBx.setObjectName("NumberOfSpansSpnBx")
        self.horizontalLayout_6.addWidget(self.NumberOfSpansSpnBx)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.CurrentShapeControlsLbl = QtWidgets.QLabel(self.RebuildGrp)
        self.CurrentShapeControlsLbl.setText("")
        self.CurrentShapeControlsLbl.setObjectName("CurrentShapeControlsLbl")
        self.verticalLayout.addWidget(self.CurrentShapeControlsLbl)
        self.verticalLayout_6.addWidget(self.RebuildGrp)
        self.groupBox_2 = QtWidgets.QGroupBox(self.LacesGrpBx)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.X_offsetAxis_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.X_offsetAxis_radio.setChecked(False)
        self.X_offsetAxis_radio.setObjectName("X_offsetAxis_radio")
        self.horizontalLayout_9.addWidget(self.X_offsetAxis_radio)
        self.Y_offsetAxis_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.Y_offsetAxis_radio.setChecked(True)
        self.Y_offsetAxis_radio.setObjectName("Y_offsetAxis_radio")
        self.horizontalLayout_9.addWidget(self.Y_offsetAxis_radio)
        self.Z_offsetAxis_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.Z_offsetAxis_radio.setObjectName("Z_offsetAxis_radio")
        self.horizontalLayout_9.addWidget(self.Z_offsetAxis_radio)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addWidget(self.LacesGrpBx)
        self.progresivePathGrpBx = QtWidgets.QGroupBox(Form)
        self.progresivePathGrpBx.setObjectName("progresivePathGrpBx")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.progresivePathGrpBx)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PathCurveBtn = QtWidgets.QPushButton(self.progresivePathGrpBx)
        self.PathCurveBtn.setObjectName("PathCurveBtn")
        self.horizontalLayout_4.addWidget(self.PathCurveBtn)
        self.PathCurveLbl = QtWidgets.QLabel(self.progresivePathGrpBx)
        self.PathCurveLbl.setText("")
        self.PathCurveLbl.setObjectName("PathCurveLbl")
        self.horizontalLayout_4.addWidget(self.PathCurveLbl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ControlCurveBtn = QtWidgets.QPushButton(self.progresivePathGrpBx)
        self.ControlCurveBtn.setObjectName("ControlCurveBtn")
        self.horizontalLayout_5.addWidget(self.ControlCurveBtn)
        self.ControlCurveLbl = QtWidgets.QLabel(self.progresivePathGrpBx)
        self.ControlCurveLbl.setText("")
        self.ControlCurveLbl.setObjectName("ControlCurveLbl")
        self.horizontalLayout_5.addWidget(self.ControlCurveLbl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.pushButton = QtWidgets.QPushButton(self.progresivePathGrpBx)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.progresivePathGrpBx)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SinCntrlCurveBtn = QtWidgets.QPushButton(self.groupBox)
        self.SinCntrlCurveBtn.setObjectName("SinCntrlCurveBtn")
        self.horizontalLayout_3.addWidget(self.SinCntrlCurveBtn)
        self.SinCurveLbl = QtWidgets.QLabel(self.groupBox)
        self.SinCurveLbl.setMinimumSize(QtCore.QSize(100, 0))
        self.SinCurveLbl.setText("")
        self.SinCurveLbl.setObjectName("SinCurveLbl")
        self.horizontalLayout_3.addWidget(self.SinCurveLbl)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CreateSinBtn = QtWidgets.QPushButton(self.groupBox)
        self.CreateSinBtn.setObjectName("CreateSinBtn")
        self.horizontalLayout_7.addWidget(self.CreateSinBtn)
        self.XchkBx = QtWidgets.QCheckBox(self.groupBox)
        self.XchkBx.setObjectName("XchkBx")
        self.horizontalLayout_7.addWidget(self.XchkBx)
        self.YchkBx = QtWidgets.QCheckBox(self.groupBox)
        self.YchkBx.setChecked(True)
        self.YchkBx.setObjectName("YchkBx")
        self.horizontalLayout_7.addWidget(self.YchkBx)
        self.ZchkBx = QtWidgets.QCheckBox(self.groupBox)
        self.ZchkBx.setObjectName("ZchkBx")
        self.horizontalLayout_7.addWidget(self.ZchkBx)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.LacesGrpBx.setTitle(QtWidgets.QApplication.translate("Form", "Lace creation", None, -1))
        self.LoadShapeBtn.setText(QtWidgets.QApplication.translate("Form", "Load Selected Shape", None, -1))
        self.CurrentShapeLbl.setText(QtWidgets.QApplication.translate("Form", "No Shape Selected", None, -1))
        self.JointsOnCurve.setText(QtWidgets.QApplication.translate("Form", "Joints On curve", None, -1))
        self.Mode.setText(QtWidgets.QApplication.translate("Form", "Single orient object", None, -1))
        self.CreateControlsBtn.setText(QtWidgets.QApplication.translate("Form", "Create Controls", None, -1))
        self.RebuildGrp.setTitle(QtWidgets.QApplication.translate("Form", "Rebuild curve", None, -1))
        self.RebuildCurveChk.setText(QtWidgets.QApplication.translate("Form", "rebuild curve", None, -1))
        self.NumberofSpansLabel.setText(QtWidgets.QApplication.translate("Form", "number of Controls", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Form", "Offset", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "Axis:", None, -1))
        self.X_offsetAxis_radio.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.Y_offsetAxis_radio.setText(QtWidgets.QApplication.translate("Form", "Y", None, -1))
        self.Z_offsetAxis_radio.setText(QtWidgets.QApplication.translate("Form", "Z", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "Value:", None, -1))
        self.progresivePathGrpBx.setTitle(QtWidgets.QApplication.translate("Form", "Progresive Path", None, -1))
        self.PathCurveBtn.setText(QtWidgets.QApplication.translate("Form", "Load Path Curve :", None, -1))
        self.ControlCurveBtn.setText(QtWidgets.QApplication.translate("Form", "Load Control Curve:", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form", "Progresive link to Path", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Form", "Sin function ", None, -1))
        self.SinCntrlCurveBtn.setText(QtWidgets.QApplication.translate("Form", "Load control curve :", None, -1))
        self.CreateSinBtn.setText(QtWidgets.QApplication.translate("Form", "Create sin function on selection", None, -1))
        self.XchkBx.setText(QtWidgets.QApplication.translate("Form", "X", None, -1))
        self.YchkBx.setText(QtWidgets.QApplication.translate("Form", "Y", None, -1))
        self.ZchkBx.setText(QtWidgets.QApplication.translate("Form", "Z", None, -1))

