# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RMFormLaces.ui'
#
# Created: Mon Oct 31 15:31:46 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

try:
    from PySide2.QtCore import *
    from PySide2.QtGui import *
    from PySide2.QtWidgets import *
    from PySide2 import __version__
    from shiboken2 import wrapInstance
except ImportError:
    from PySide.QtCore import *
    from PySide.QtGui import *
    from PySide import __version__
    from shiboken import wrapInstance

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(354, 435)
        self.verticalLayout_3 = QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LacesGrpBx = QGroupBox(Form)
        self.LacesGrpBx.setObjectName("LacesGrpBx")
        self.horizontalLayout_2 = QHBoxLayout(self.LacesGrpBx)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LoadShapeBtn = QPushButton(self.LacesGrpBx)
        self.LoadShapeBtn.setObjectName("LoadShapeBtn")
        self.verticalLayout_2.addWidget(self.LoadShapeBtn)
        self.CurrentShapeLbl = QLabel(self.LacesGrpBx)
        self.CurrentShapeLbl.setAlignment(Qt.AlignCenter)
        self.CurrentShapeLbl.setObjectName("CurrentShapeLbl")
        self.verticalLayout_2.addWidget(self.CurrentShapeLbl)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.JointsOnCurve = QLabel(self.LacesGrpBx)
        self.JointsOnCurve.setObjectName("JointsOnCurve")
        self.horizontalLayout.addWidget(self.JointsOnCurve)
        self.NumberOfJoints = QSpinBox(self.LacesGrpBx)
        self.NumberOfJoints.setMinimumSize(QSize(50, 0))
        self.NumberOfJoints.setMaximumSize(QSize(50, 16777215))
        self.NumberOfJoints.setMinimum(2)
        self.NumberOfJoints.setProperty("value", 2)
        self.NumberOfJoints.setObjectName("NumberOfJoints")
        self.horizontalLayout.addWidget(self.NumberOfJoints)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.Mode = QCheckBox(self.LacesGrpBx)
        self.Mode.setLayoutDirection(Qt.LeftToRight)
        self.Mode.setCheckable(True)
        self.Mode.setChecked(False)
        self.Mode.setObjectName("Mode")
        self.verticalLayout_2.addWidget(self.Mode)
        self.CreateControlsBtn = QPushButton(self.LacesGrpBx)
        self.CreateControlsBtn.setObjectName("CreateControlsBtn")
        self.verticalLayout_2.addWidget(self.CreateControlsBtn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.RebuildGrp = QGroupBox(self.LacesGrpBx)
        self.RebuildGrp.setObjectName("RebuildGrp")
        self.verticalLayout = QVBoxLayout(self.RebuildGrp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RebuildCurveChk = QCheckBox(self.RebuildGrp)
        self.RebuildCurveChk.setObjectName("RebuildCurveChk")
        self.verticalLayout.addWidget(self.RebuildCurveChk)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.NumberofSpansLabel = QLabel(self.RebuildGrp)
        self.NumberofSpansLabel.setObjectName("NumberofSpansLabel")
        self.horizontalLayout_6.addWidget(self.NumberofSpansLabel)
        self.NumberOfSpansSpnBx = QSpinBox(self.RebuildGrp)
        self.NumberOfSpansSpnBx.setMinimumSize(QSize(50, 0))
        self.NumberOfSpansSpnBx.setMaximumSize(QSize(50, 16777215))
        self.NumberOfSpansSpnBx.setMinimum(4)
        self.NumberOfSpansSpnBx.setObjectName("NumberOfSpansSpnBx")
        self.horizontalLayout_6.addWidget(self.NumberOfSpansSpnBx)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.CurrentShapeControlsLbl = QLabel(self.RebuildGrp)
        self.CurrentShapeControlsLbl.setText("")
        self.CurrentShapeControlsLbl.setObjectName("CurrentShapeControlsLbl")
        self.verticalLayout.addWidget(self.CurrentShapeControlsLbl)
        self.horizontalLayout_2.addWidget(self.RebuildGrp)
        self.verticalLayout_3.addWidget(self.LacesGrpBx)
        self.progresivePathGrpBx = QGroupBox(Form)
        self.progresivePathGrpBx.setObjectName("progresivePathGrpBx")
        self.verticalLayout_4 = QVBoxLayout(self.progresivePathGrpBx)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PathCurveBtn = QPushButton(self.progresivePathGrpBx)
        self.PathCurveBtn.setObjectName("PathCurveBtn")
        self.horizontalLayout_4.addWidget(self.PathCurveBtn)
        self.PathCurveLbl = QLabel(self.progresivePathGrpBx)
        self.PathCurveLbl.setText("")
        self.PathCurveLbl.setObjectName("PathCurveLbl")
        self.horizontalLayout_4.addWidget(self.PathCurveLbl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ControlCurveBtn = QPushButton(self.progresivePathGrpBx)
        self.ControlCurveBtn.setObjectName("ControlCurveBtn")
        self.horizontalLayout_5.addWidget(self.ControlCurveBtn)
        self.ControlCurveLbl = QLabel(self.progresivePathGrpBx)
        self.ControlCurveLbl.setText("")
        self.ControlCurveLbl.setObjectName("ControlCurveLbl")
        self.horizontalLayout_5.addWidget(self.ControlCurveLbl)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.pushButton = QPushButton(self.progresivePathGrpBx)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.progresivePathGrpBx)
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SinCntrlCurveBtn = QPushButton(self.groupBox)
        self.SinCntrlCurveBtn.setObjectName("SinCntrlCurveBtn")
        self.horizontalLayout_3.addWidget(self.SinCntrlCurveBtn)
        self.SinCurveLbl = QLabel(self.groupBox)
        self.SinCurveLbl.setMinimumSize(QSize(100, 0))
        self.SinCurveLbl.setText("")
        self.SinCurveLbl.setObjectName("SinCurveLbl")
        self.horizontalLayout_3.addWidget(self.SinCurveLbl)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CreateSinBtn = QPushButton(self.groupBox)
        self.CreateSinBtn.setObjectName("CreateSinBtn")
        self.horizontalLayout_7.addWidget(self.CreateSinBtn)
        self.XchkBx = QCheckBox(self.groupBox)
        self.XchkBx.setObjectName("XchkBx")
        self.horizontalLayout_7.addWidget(self.XchkBx)
        self.YchkBx = QCheckBox(self.groupBox)
        self.YchkBx.setChecked(True)
        self.YchkBx.setObjectName("YchkBx")
        self.horizontalLayout_7.addWidget(self.YchkBx)
        self.ZchkBx = QCheckBox(self.groupBox)
        self.ZchkBx.setObjectName("ZchkBx")
        self.horizontalLayout_7.addWidget(self.ZchkBx)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QApplication.translate("Form", "Form", None, -1))
        self.LacesGrpBx.setTitle(QApplication.translate("Form", "Lace creation", None, -1))
        self.LoadShapeBtn.setText(QApplication.translate("Form", "Load Selected Shape", None, -1))
        self.CurrentShapeLbl.setText(QApplication.translate("Form", "No Shape Selected", None, -1))
        self.JointsOnCurve.setText(QApplication.translate("Form", "Joints On curve", None, -1))
        self.Mode.setText(QApplication.translate("Form", "Single orient object", None, -1))
        self.CreateControlsBtn.setText(QApplication.translate("Form", "Create Controls", None, -1))
        self.RebuildGrp.setTitle(QApplication.translate("Form", "Rebuild curve", None, -1))
        self.RebuildCurveChk.setText(QApplication.translate("Form", "rebuild curve", None, -1))
        self.NumberofSpansLabel.setText(QApplication.translate("Form", "number of Controls", None, -1))
        self.progresivePathGrpBx.setTitle(QApplication.translate("Form", "Progresive Path", None, -1))
        self.PathCurveBtn.setText(QApplication.translate("Form", "Load Path Curve :", None, -1))
        self.ControlCurveBtn.setText(QApplication.translate("Form", "Load Control Curve:", None, -1))
        self.pushButton.setText(QApplication.translate("Form", "Progresive link to Path", None, -1))
        self.groupBox.setTitle(QApplication.translate("Form", "Sin function ", None, -1))
        self.SinCntrlCurveBtn.setText(QApplication.translate("Form", "Load control curve :", None, -1))
        self.CreateSinBtn.setText(QApplication.translate("Form", "Create sin function on selection", None, -1))
        self.XchkBx.setText(QApplication.translate("Form", "X", None, -1))
        self.YchkBx.setText(QApplication.translate("Form", "Y", None, -1))
        self.ZchkBx.setText(QApplication.translate("Form", "Z", None, -1))

