# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RMINTRigTools.ui'
#
# Created: Mon Oct 31 15:31:38 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

try:
    from PySide2.QtCore import *
    from PySide2.QtGui import *
    from PySide2.QtWidgets import *
    from PySide2 import __version__
    from shiboken2 import wrapInstance
except ImportError:
    from PySide.QtCore import *
    from PySide.QtGui import *
    from PySide import __version__
    from shiboken import wrapInstance

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(485, 669)
        self.verticalLayout_13 = QVBoxLayout(Form)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_17 = QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.MiscGroupBox = QGroupBox(Form)
        self.MiscGroupBox.setObjectName("MiscGroupBox")
        self.verticalLayout_4 = QVBoxLayout(self.MiscGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RenameTool = QPushButton(self.MiscGroupBox)
        self.RenameTool.setObjectName("RenameTool")
        self.verticalLayout_4.addWidget(self.RenameTool)
        self.ExtractGeoBtn = QPushButton(self.MiscGroupBox)
        self.ExtractGeoBtn.setObjectName("ExtractGeoBtn")
        self.verticalLayout_4.addWidget(self.ExtractGeoBtn)
        self.ParentConstraintBtn = QPushButton(self.MiscGroupBox)
        self.ParentConstraintBtn.setObjectName("ParentConstraintBtn")
        self.verticalLayout_4.addWidget(self.ParentConstraintBtn)
        self.AttributeTransferBtn = QPushButton(self.MiscGroupBox)
        self.AttributeTransferBtn.setToolTip("")
        self.AttributeTransferBtn.setObjectName("AttributeTransferBtn")
        self.verticalLayout_4.addWidget(self.AttributeTransferBtn)
        self.verticalLayout_17.addWidget(self.MiscGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_17)
        self.verticalLayout_11 = QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ConstShapeLblBtn = QPushButton(self.groupBox)
        self.ConstShapeLblBtn.setObjectName("ConstShapeLblBtn")
        self.verticalLayout_9.addWidget(self.ConstShapeLblBtn)
        self.SCCombineButton = QPushButton(self.groupBox)
        self.SCCombineButton.setObjectName("SCCombineButton")
        self.verticalLayout_9.addWidget(self.SCCombineButton)
        self.CopyCvsPosBtn = QPushButton(self.groupBox)
        self.CopyCvsPosBtn.setObjectName("CopyCvsPosBtn")
        self.verticalLayout_9.addWidget(self.CopyCvsPosBtn)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.AlignGroupBox = QGroupBox(Form)
        self.AlignGroupBox.setObjectName("AlignGroupBox")
        self.verticalLayout_10 = QVBoxLayout(self.AlignGroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.AlignRotation = QPushButton(self.AlignGroupBox)
        self.AlignRotation.setObjectName("AlignRotation")
        self.verticalLayout_10.addWidget(self.AlignRotation)
        self.AlignPosition = QPushButton(self.AlignGroupBox)
        self.AlignPosition.setObjectName("AlignPosition")
        self.verticalLayout_10.addWidget(self.AlignPosition)
        self.AlignAll = QPushButton(self.AlignGroupBox)
        self.AlignAll.setObjectName("AlignAll")
        self.verticalLayout_10.addWidget(self.AlignAll)
        self.verticalLayout_11.addWidget(self.AlignGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.GroupsGroupBox = QGroupBox(Form)
        self.GroupsGroupBox.setObjectName("GroupsGroupBox")
        self.verticalLayout = QVBoxLayout(self.GroupsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CreateChildGroup = QPushButton(self.GroupsGroupBox)
        self.CreateChildGroup.setObjectName("CreateChildGroup")
        self.verticalLayout.addWidget(self.CreateChildGroup)
        self.groupBox_2 = QGroupBox(self.GroupsGroupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.worldRadio = QRadioButton(self.groupBox_2)
        self.worldRadio.setObjectName("worldRadio")
        self.horizontalLayout_8.addWidget(self.worldRadio)
        self.parentRadio = QRadioButton(self.groupBox_2)
        self.parentRadio.setObjectName("parentRadio")
        self.horizontalLayout_8.addWidget(self.parentRadio)
        self.insertedRadio = QRadioButton(self.groupBox_2)
        self.insertedRadio.setChecked(True)
        self.insertedRadio.setObjectName("insertedRadio")
        self.horizontalLayout_8.addWidget(self.insertedRadio)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.CreateParentGroup = QPushButton(self.groupBox_2)
        self.CreateParentGroup.setObjectName("CreateParentGroup")
        self.verticalLayout_7.addWidget(self.CreateParentGroup)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.JointsGroupBox = QGroupBox(self.GroupsGroupBox)
        self.JointsGroupBox.setObjectName("JointsGroupBox")
        self.verticalLayout_8 = QVBoxLayout(self.JointsGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.JointsOnPoints = QPushButton(self.JointsGroupBox)
        self.JointsOnPoints.setObjectName("JointsOnPoints")
        self.verticalLayout_8.addWidget(self.JointsOnPoints)
        self.OrientNubButton = QPushButton(self.JointsGroupBox)
        self.OrientNubButton.setObjectName("OrientNubButton")
        self.verticalLayout_8.addWidget(self.OrientNubButton)
        self.verticalLayout.addWidget(self.JointsGroupBox)
        self.horizontalLayout.addWidget(self.GroupsGroupBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.line = QFrame(Form)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RigGroupBox = QGroupBox(Form)
        self.RigGroupBox.setObjectName("RigGroupBox")
        self.verticalLayout_2 = QVBoxLayout(self.RigGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FKOnSelection = QPushButton(self.RigGroupBox)
        self.FKOnSelection.setObjectName("FKOnSelection")
        self.verticalLayout_2.addWidget(self.FKOnSelection)
        self.IKOnSelection = QPushButton(self.RigGroupBox)
        self.IKOnSelection.setObjectName("IKOnSelection")
        self.verticalLayout_2.addWidget(self.IKOnSelection)
        self.GenericJointChainRigBtn = QPushButton(self.RigGroupBox)
        self.GenericJointChainRigBtn.setObjectName("GenericJointChainRigBtn")
        self.verticalLayout_2.addWidget(self.GenericJointChainRigBtn)
        self.groupBox_3 = QGroupBox(self.RigGroupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.MainProgresiveLayout = QVBoxLayout()
        self.MainProgresiveLayout.setObjectName("MainProgresiveLayout")
        self.label = QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.MainProgresiveLayout.addWidget(self.label)
        self.ProgressiveDepthSpinBox = QSpinBox(self.groupBox_3)
        self.ProgressiveDepthSpinBox.setMinimum(1)
        self.ProgressiveDepthSpinBox.setProperty("value", 1)
        self.ProgressiveDepthSpinBox.setObjectName("ProgressiveDepthSpinBox")
        self.MainProgresiveLayout.addWidget(self.ProgressiveDepthSpinBox)
        self.ProgressiveConstraintButton = QPushButton(self.groupBox_3)
        self.ProgressiveConstraintButton.setObjectName("ProgressiveConstraintButton")
        self.MainProgresiveLayout.addWidget(self.ProgressiveConstraintButton)
        self.mantainOffsetChk = QCheckBox(self.groupBox_3)
        self.mantainOffsetChk.setChecked(True)
        self.mantainOffsetChk.setObjectName("mantainOffsetChk")
        self.MainProgresiveLayout.addWidget(self.mantainOffsetChk)
        self.horizontalLayout_5.addLayout(self.MainProgresiveLayout)
        self.ProgressiveTypeLayout = QVBoxLayout()
        self.ProgressiveTypeLayout.setObjectName("ProgressiveTypeLayout")
        self.CnstParentRadio = QRadioButton(self.groupBox_3)
        self.CnstParentRadio.setObjectName("CnstParentRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstParentRadio)
        self.CnstOrientRadio = QRadioButton(self.groupBox_3)
        self.CnstOrientRadio.setChecked(True)
        self.CnstOrientRadio.setObjectName("CnstOrientRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstOrientRadio)
        self.CnstPointRadio = QRadioButton(self.groupBox_3)
        self.CnstPointRadio.setObjectName("CnstPointRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstPointRadio)
        self.horizontalLayout_5.addLayout(self.ProgressiveTypeLayout)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.unfoldRigGrpBox = QGroupBox(self.RigGroupBox)
        self.unfoldRigGrpBox.setObjectName("unfoldRigGrpBox")
        self.verticalLayout_5 = QVBoxLayout(self.unfoldRigGrpBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_12 = QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.initRadiusLbl = QLabel(self.unfoldRigGrpBox)
        self.initRadiusLbl.setObjectName("initRadiusLbl")
        self.horizontalLayout_4.addWidget(self.initRadiusLbl)
        self.initRadiusSpnBx = QDoubleSpinBox(self.unfoldRigGrpBox)
        self.initRadiusSpnBx.setObjectName("initRadiusSpnBx")
        self.horizontalLayout_4.addWidget(self.initRadiusSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.endRadiusLbl = QLabel(self.unfoldRigGrpBox)
        self.endRadiusLbl.setObjectName("endRadiusLbl")
        self.horizontalLayout_6.addWidget(self.endRadiusLbl)
        self.endRadiusSpnBx = QDoubleSpinBox(self.unfoldRigGrpBox)
        self.endRadiusSpnBx.setObjectName("endRadiusSpnBx")
        self.horizontalLayout_6.addWidget(self.endRadiusSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.numberOfPointsLbl = QLabel(self.unfoldRigGrpBox)
        self.numberOfPointsLbl.setObjectName("numberOfPointsLbl")
        self.horizontalLayout_7.addWidget(self.numberOfPointsLbl)
        self.NumberOfPointsSpnBx = QSpinBox(self.unfoldRigGrpBox)
        self.NumberOfPointsSpnBx.setObjectName("NumberOfPointsSpnBx")
        self.horizontalLayout_7.addWidget(self.NumberOfPointsSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.unfoldRigBtn = QPushButton(self.unfoldRigGrpBox)
        self.unfoldRigBtn.setObjectName("unfoldRigBtn")
        self.verticalLayout_12.addWidget(self.unfoldRigBtn)
        self.verticalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_2.addWidget(self.unfoldRigGrpBox)
        self.horizontalLayout_2.addWidget(self.RigGroupBox)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QFrame(Form)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.SkiningToolslabel = QLabel(Form)
        self.SkiningToolslabel.setObjectName("SkiningToolslabel")
        self.verticalLayout_3.addWidget(self.SkiningToolslabel)
        self.ListConnectedJoints = QPushButton(Form)
        self.ListConnectedJoints.setObjectName("ListConnectedJoints")
        self.verticalLayout_3.addWidget(self.ListConnectedJoints)
        self.listWidget = QListWidget(Form)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.SelectJoints = QPushButton(Form)
        self.SelectJoints.setObjectName("SelectJoints")
        self.verticalLayout_3.addWidget(self.SelectJoints)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_13.addLayout(self.verticalLayout_6)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QApplication.translate("Form", "Form", None, -1))
        self.MiscGroupBox.setTitle(QApplication.translate("Form", "Misc", None, -1))
        self.RenameTool.setText(QApplication.translate("Form", "Rename Tool", None, -1))
        self.ExtractGeoBtn.setText(QApplication.translate("Form", "ExtractGeometry", None, -1))
        self.ParentConstraintBtn.setText(QApplication.translate("Form", "Parent Constraint", None, -1))
        self.AttributeTransferBtn.setText(QApplication.translate("Form", "Move Attributes", None, -1))
        self.groupBox.setTitle(QApplication.translate("Form", "EditShapes", None, -1))
        self.ConstShapeLblBtn.setText(QApplication.translate("Form", "Const Shape Lbl", None, -1))
        self.SCCombineButton.setText(QApplication.translate("Form", "Combine", None, -1))
        self.CopyCvsPosBtn.setText(QApplication.translate("Form", "Copy Cvs Position", None, -1))
        self.AlignGroupBox.setTitle(QApplication.translate("Form", "Align Tools", None, -1))
        self.AlignRotation.setText(QApplication.translate("Form", "AlignRotation", None, -1))
        self.AlignPosition.setText(QApplication.translate("Form", "AlignPosition", None, -1))
        self.AlignAll.setText(QApplication.translate("Form", "Align Pos & Rot", None, -1))
        self.GroupsGroupBox.setTitle(QApplication.translate("Form", "Group Creation", None, -1))
        self.CreateChildGroup.setText(QApplication.translate("Form", "Create Child Group", None, -1))
        self.groupBox_2.setTitle(QApplication.translate("Form", "Parent Group", None, -1))
        self.worldRadio.setText(QApplication.translate("Form", "world", None, -1))
        self.parentRadio.setText(QApplication.translate("Form", "parent", None, -1))
        self.insertedRadio.setText(QApplication.translate("Form", "inserted", None, -1))
        self.CreateParentGroup.setText(QApplication.translate("Form", "Create Parent Group", None, -1))
        self.JointsGroupBox.setTitle(QApplication.translate("Form", "Joints", None, -1))
        self.JointsOnPoints.setText(QApplication.translate("Form", "CreateJointsOnPoints", None, -1))
        self.OrientNubButton.setText(QApplication.translate("Form", "Orient Nub", None, -1))
        self.RigGroupBox.setTitle(QApplication.translate("Form", "Rig", None, -1))
        self.FKOnSelection.setToolTip(QApplication.translate("Form", "Select some locators in order to create an FK Control", None, -1))
        self.FKOnSelection.setText(QApplication.translate("Form", "FK on selection", None, -1))
        self.IKOnSelection.setToolTip(QApplication.translate("Form", "Select some locators in order to create an FK Control", None, -1))
        self.IKOnSelection.setText(QApplication.translate("Form", "IK on selection", None, -1))
        self.GenericJointChainRigBtn.setText(QApplication.translate("Form", "Generic Joint Chain Rig", None, -1))
        self.groupBox_3.setTitle(QApplication.translate("Form", "Progressive Constraint", None, -1))
        self.label.setText(QApplication.translate("Form", "Depth", None, -1))
        self.ProgressiveConstraintButton.setText(QApplication.translate("Form", "Progressive Constraint", None, -1))
        self.mantainOffsetChk.setText(QApplication.translate("Form", "mantain offset", None, -1))
        self.CnstParentRadio.setText(QApplication.translate("Form", "parent", None, -1))
        self.CnstOrientRadio.setText(QApplication.translate("Form", "orient", None, -1))
        self.CnstPointRadio.setText(QApplication.translate("Form", "point", None, -1))
        self.unfoldRigGrpBox.setTitle(QApplication.translate("Form", "Unfold Rig", None, -1))
        self.initRadiusLbl.setText(QApplication.translate("Form", "Init Radius", None, -1))
        self.endRadiusLbl.setText(QApplication.translate("Form", "End Radius", None, -1))
        self.numberOfPointsLbl.setText(QApplication.translate("Form", "Number Of Points", None, -1))
        self.unfoldRigBtn.setText(QApplication.translate("Form", "unfold Rig", None, -1))
        self.SkiningToolslabel.setText(QApplication.translate("Form", "SkiningTools", None, -1))
        self.ListConnectedJoints.setText(QApplication.translate("Form", "List Skined Joints", None, -1))
        self.SelectJoints.setText(QApplication.translate("Form", "Select Joints", None, -1))

