# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_RigTools.ui'
#
# Created: Wed Mar 21 21:43:33 2018
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(516, 698)
        self.verticalLayout_13 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.MiscGroupBox = QtGui.QGroupBox(Form)
        self.MiscGroupBox.setObjectName("MiscGroupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.MiscGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RenameTool = QtGui.QPushButton(self.MiscGroupBox)
        self.RenameTool.setEnabled(False)
        self.RenameTool.setObjectName("RenameTool")
        self.verticalLayout_4.addWidget(self.RenameTool)
        self.ExtractGeoBtn = QtGui.QPushButton(self.MiscGroupBox)
        self.ExtractGeoBtn.setObjectName("ExtractGeoBtn")
        self.verticalLayout_4.addWidget(self.ExtractGeoBtn)
        self.ParentConstraintBtn = QtGui.QPushButton(self.MiscGroupBox)
        self.ParentConstraintBtn.setObjectName("ParentConstraintBtn")
        self.verticalLayout_4.addWidget(self.ParentConstraintBtn)
        self.AttributeTransferBtn = QtGui.QPushButton(self.MiscGroupBox)
        self.AttributeTransferBtn.setToolTip("")
        self.AttributeTransferBtn.setObjectName("AttributeTransferBtn")
        self.verticalLayout_4.addWidget(self.AttributeTransferBtn)
        self.verticalLayout_17.addWidget(self.MiscGroupBox)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.create_locators_at_nodes_btn = QtGui.QPushButton(self.groupBox_4)
        self.create_locators_at_nodes_btn.setObjectName("create_locators_at_nodes_btn")
        self.verticalLayout_14.addWidget(self.create_locators_at_nodes_btn)
        self.three_points_locators_btn = QtGui.QPushButton(self.groupBox_4)
        self.three_points_locators_btn.setObjectName("three_points_locators_btn")
        self.verticalLayout_14.addWidget(self.three_points_locators_btn)
        self.locator_at_average_btn = QtGui.QPushButton(self.groupBox_4)
        self.locator_at_average_btn.setObjectName("locator_at_average_btn")
        self.verticalLayout_14.addWidget(self.locator_at_average_btn)
        self.verticalLayout_17.addWidget(self.groupBox_4)
        self.horizontalLayout.addLayout(self.verticalLayout_17)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ConstShapeLblBtn = QtGui.QPushButton(self.groupBox)
        self.ConstShapeLblBtn.setObjectName("ConstShapeLblBtn")
        self.verticalLayout_9.addWidget(self.ConstShapeLblBtn)
        self.SCCombineButton = QtGui.QPushButton(self.groupBox)
        self.SCCombineButton.setObjectName("SCCombineButton")
        self.verticalLayout_9.addWidget(self.SCCombineButton)
        self.CopyCvsPosBtn = QtGui.QPushButton(self.groupBox)
        self.CopyCvsPosBtn.setObjectName("CopyCvsPosBtn")
        self.verticalLayout_9.addWidget(self.CopyCvsPosBtn)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.AlignGroupBox = QtGui.QGroupBox(Form)
        self.AlignGroupBox.setObjectName("AlignGroupBox")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.AlignGroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.AlignPosition = QtGui.QPushButton(self.AlignGroupBox)
        self.AlignPosition.setObjectName("AlignPosition")
        self.verticalLayout_10.addWidget(self.AlignPosition)
        self.AlignRotation = QtGui.QPushButton(self.AlignGroupBox)
        self.AlignRotation.setObjectName("AlignRotation")
        self.verticalLayout_10.addWidget(self.AlignRotation)
        self.AlignAll = QtGui.QPushButton(self.AlignGroupBox)
        self.AlignAll.setObjectName("AlignAll")
        self.verticalLayout_10.addWidget(self.AlignAll)
        self.align_at_locator = QtGui.QPushButton(self.AlignGroupBox)
        self.align_at_locator.setObjectName("align_at_locator")
        self.verticalLayout_10.addWidget(self.align_at_locator)
        self.verticalLayout_11.addWidget(self.AlignGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.GroupsGroupBox = QtGui.QGroupBox(Form)
        self.GroupsGroupBox.setObjectName("GroupsGroupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.GroupsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CreateChildGroup = QtGui.QPushButton(self.GroupsGroupBox)
        self.CreateChildGroup.setObjectName("CreateChildGroup")
        self.verticalLayout.addWidget(self.CreateChildGroup)
        self.groupBox_2 = QtGui.QGroupBox(self.GroupsGroupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.worldRadio = QtGui.QRadioButton(self.groupBox_2)
        self.worldRadio.setObjectName("worldRadio")
        self.horizontalLayout_8.addWidget(self.worldRadio)
        self.parentRadio = QtGui.QRadioButton(self.groupBox_2)
        self.parentRadio.setObjectName("parentRadio")
        self.horizontalLayout_8.addWidget(self.parentRadio)
        self.insertedRadio = QtGui.QRadioButton(self.groupBox_2)
        self.insertedRadio.setChecked(True)
        self.insertedRadio.setObjectName("insertedRadio")
        self.horizontalLayout_8.addWidget(self.insertedRadio)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.CreateParentGroup = QtGui.QPushButton(self.groupBox_2)
        self.CreateParentGroup.setObjectName("CreateParentGroup")
        self.verticalLayout_7.addWidget(self.CreateParentGroup)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.JointsGroupBox = QtGui.QGroupBox(self.GroupsGroupBox)
        self.JointsGroupBox.setObjectName("JointsGroupBox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.JointsGroupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.JointsOnPoints = QtGui.QPushButton(self.JointsGroupBox)
        self.JointsOnPoints.setObjectName("JointsOnPoints")
        self.verticalLayout_8.addWidget(self.JointsOnPoints)
        self.OrientNubButton = QtGui.QPushButton(self.JointsGroupBox)
        self.OrientNubButton.setObjectName("OrientNubButton")
        self.verticalLayout_8.addWidget(self.OrientNubButton)
        self.verticalLayout.addWidget(self.JointsGroupBox)
        self.horizontalLayout.addWidget(self.GroupsGroupBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RigGroupBox = QtGui.QGroupBox(Form)
        self.RigGroupBox.setObjectName("RigGroupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.RigGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FKOnSelection = QtGui.QPushButton(self.RigGroupBox)
        self.FKOnSelection.setObjectName("FKOnSelection")
        self.verticalLayout_2.addWidget(self.FKOnSelection)
        self.IKOnSelection = QtGui.QPushButton(self.RigGroupBox)
        self.IKOnSelection.setObjectName("IKOnSelection")
        self.verticalLayout_2.addWidget(self.IKOnSelection)
        self.GenericJointChainRigBtn = QtGui.QPushButton(self.RigGroupBox)
        self.GenericJointChainRigBtn.setObjectName("GenericJointChainRigBtn")
        self.verticalLayout_2.addWidget(self.GenericJointChainRigBtn)
        self.groupBox_3 = QtGui.QGroupBox(self.RigGroupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.MainProgresiveLayout = QtGui.QVBoxLayout()
        self.MainProgresiveLayout.setObjectName("MainProgresiveLayout")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.MainProgresiveLayout.addWidget(self.label)
        self.ProgressiveDepthSpinBox = QtGui.QSpinBox(self.groupBox_3)
        self.ProgressiveDepthSpinBox.setMinimum(1)
        self.ProgressiveDepthSpinBox.setProperty("value", 1)
        self.ProgressiveDepthSpinBox.setObjectName("ProgressiveDepthSpinBox")
        self.MainProgresiveLayout.addWidget(self.ProgressiveDepthSpinBox)
        self.ProgressiveConstraintButton = QtGui.QPushButton(self.groupBox_3)
        self.ProgressiveConstraintButton.setObjectName("ProgressiveConstraintButton")
        self.MainProgresiveLayout.addWidget(self.ProgressiveConstraintButton)
        self.mantainOffsetChk = QtGui.QCheckBox(self.groupBox_3)
        self.mantainOffsetChk.setChecked(True)
        self.mantainOffsetChk.setObjectName("mantainOffsetChk")
        self.MainProgresiveLayout.addWidget(self.mantainOffsetChk)
        self.horizontalLayout_5.addLayout(self.MainProgresiveLayout)
        self.ProgressiveTypeLayout = QtGui.QVBoxLayout()
        self.ProgressiveTypeLayout.setObjectName("ProgressiveTypeLayout")
        self.CnstParentRadio = QtGui.QRadioButton(self.groupBox_3)
        self.CnstParentRadio.setObjectName("CnstParentRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstParentRadio)
        self.CnstOrientRadio = QtGui.QRadioButton(self.groupBox_3)
        self.CnstOrientRadio.setChecked(True)
        self.CnstOrientRadio.setObjectName("CnstOrientRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstOrientRadio)
        self.CnstPointRadio = QtGui.QRadioButton(self.groupBox_3)
        self.CnstPointRadio.setObjectName("CnstPointRadio")
        self.ProgressiveTypeLayout.addWidget(self.CnstPointRadio)
        self.horizontalLayout_5.addLayout(self.ProgressiveTypeLayout)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.unfoldRigGrpBox = QtGui.QGroupBox(self.RigGroupBox)
        self.unfoldRigGrpBox.setObjectName("unfoldRigGrpBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.unfoldRigGrpBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.initRadiusLbl = QtGui.QLabel(self.unfoldRigGrpBox)
        self.initRadiusLbl.setObjectName("initRadiusLbl")
        self.horizontalLayout_4.addWidget(self.initRadiusLbl)
        self.initRadiusSpnBx = QtGui.QDoubleSpinBox(self.unfoldRigGrpBox)
        self.initRadiusSpnBx.setObjectName("initRadiusSpnBx")
        self.horizontalLayout_4.addWidget(self.initRadiusSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.endRadiusLbl = QtGui.QLabel(self.unfoldRigGrpBox)
        self.endRadiusLbl.setObjectName("endRadiusLbl")
        self.horizontalLayout_6.addWidget(self.endRadiusLbl)
        self.endRadiusSpnBx = QtGui.QDoubleSpinBox(self.unfoldRigGrpBox)
        self.endRadiusSpnBx.setObjectName("endRadiusSpnBx")
        self.horizontalLayout_6.addWidget(self.endRadiusSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.numberOfPointsLbl = QtGui.QLabel(self.unfoldRigGrpBox)
        self.numberOfPointsLbl.setObjectName("numberOfPointsLbl")
        self.horizontalLayout_7.addWidget(self.numberOfPointsLbl)
        self.NumberOfPointsSpnBx = QtGui.QSpinBox(self.unfoldRigGrpBox)
        self.NumberOfPointsSpnBx.setObjectName("NumberOfPointsSpnBx")
        self.horizontalLayout_7.addWidget(self.NumberOfPointsSpnBx)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.unfoldRigBtn = QtGui.QPushButton(self.unfoldRigGrpBox)
        self.unfoldRigBtn.setObjectName("unfoldRigBtn")
        self.verticalLayout_12.addWidget(self.unfoldRigBtn)
        self.verticalLayout_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_2.addWidget(self.unfoldRigGrpBox)
        self.horizontalLayout_2.addWidget(self.RigGroupBox)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.SkiningToolslabel = QtGui.QLabel(Form)
        self.SkiningToolslabel.setObjectName("SkiningToolslabel")
        self.verticalLayout_3.addWidget(self.SkiningToolslabel)
        self.ListConnectedJoints = QtGui.QPushButton(Form)
        self.ListConnectedJoints.setObjectName("ListConnectedJoints")
        self.verticalLayout_3.addWidget(self.ListConnectedJoints)
        self.listWidget = QtGui.QListWidget(Form)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.SelectJoints = QtGui.QPushButton(Form)
        self.SelectJoints.setObjectName("SelectJoints")
        self.verticalLayout_3.addWidget(self.SelectJoints)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_13.addLayout(self.verticalLayout_6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.MiscGroupBox.setTitle(QtGui.QApplication.translate("Form", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.RenameTool.setText(QtGui.QApplication.translate("Form", "Rename Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.ExtractGeoBtn.setText(QtGui.QApplication.translate("Form", "ExtractGeometry", None, QtGui.QApplication.UnicodeUTF8))
        self.ParentConstraintBtn.setText(QtGui.QApplication.translate("Form", "Parent Constraint", None, QtGui.QApplication.UnicodeUTF8))
        self.AttributeTransferBtn.setText(QtGui.QApplication.translate("Form", "Move Attributes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Create Locators", None, QtGui.QApplication.UnicodeUTF8))
        self.create_locators_at_nodes_btn.setText(QtGui.QApplication.translate("Form", "locator at nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.three_points_locators_btn.setToolTip(QtGui.QApplication.translate("Form", "select tree points or vertices a locator will be created over the first element, aiming to the second one, and using the third as up vector.", None, QtGui.QApplication.UnicodeUTF8))
        self.three_points_locators_btn.setText(QtGui.QApplication.translate("Form", "Three point locators", None, QtGui.QApplication.UnicodeUTF8))
        self.locator_at_average_btn.setToolTip(QtGui.QApplication.translate("Form", "select some vertex or objects and a locator will be created at the average position", None, QtGui.QApplication.UnicodeUTF8))
        self.locator_at_average_btn.setText(QtGui.QApplication.translate("Form", "locator at average", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "EditShapes", None, QtGui.QApplication.UnicodeUTF8))
        self.ConstShapeLblBtn.setText(QtGui.QApplication.translate("Form", "Const Shape Lbl", None, QtGui.QApplication.UnicodeUTF8))
        self.SCCombineButton.setText(QtGui.QApplication.translate("Form", "Combine", None, QtGui.QApplication.UnicodeUTF8))
        self.CopyCvsPosBtn.setText(QtGui.QApplication.translate("Form", "Copy Cvs Position", None, QtGui.QApplication.UnicodeUTF8))
        self.AlignGroupBox.setTitle(QtGui.QApplication.translate("Form", "Align Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.AlignPosition.setText(QtGui.QApplication.translate("Form", "AlignPosition", None, QtGui.QApplication.UnicodeUTF8))
        self.AlignRotation.setText(QtGui.QApplication.translate("Form", "AlignRotation", None, QtGui.QApplication.UnicodeUTF8))
        self.AlignAll.setText(QtGui.QApplication.translate("Form", "Align Pos & Rot", None, QtGui.QApplication.UnicodeUTF8))
        self.align_at_locator.setToolTip(QtGui.QApplication.translate("Form", "select two objects the first will point to the second one, if you select three, the third object will be the up vector", None, QtGui.QApplication.UnicodeUTF8))
        self.align_at_locator.setText(QtGui.QApplication.translate("Form", "Align at locator", None, QtGui.QApplication.UnicodeUTF8))
        self.GroupsGroupBox.setTitle(QtGui.QApplication.translate("Form", "Group Creation", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateChildGroup.setText(QtGui.QApplication.translate("Form", "Create Child Group", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Parent Group", None, QtGui.QApplication.UnicodeUTF8))
        self.worldRadio.setText(QtGui.QApplication.translate("Form", "world", None, QtGui.QApplication.UnicodeUTF8))
        self.parentRadio.setText(QtGui.QApplication.translate("Form", "parent", None, QtGui.QApplication.UnicodeUTF8))
        self.insertedRadio.setText(QtGui.QApplication.translate("Form", "inserted", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateParentGroup.setText(QtGui.QApplication.translate("Form", "Create Parent Group", None, QtGui.QApplication.UnicodeUTF8))
        self.JointsGroupBox.setTitle(QtGui.QApplication.translate("Form", "Joints", None, QtGui.QApplication.UnicodeUTF8))
        self.JointsOnPoints.setText(QtGui.QApplication.translate("Form", "CreateJointsOnPoints", None, QtGui.QApplication.UnicodeUTF8))
        self.OrientNubButton.setText(QtGui.QApplication.translate("Form", "Orient Nub", None, QtGui.QApplication.UnicodeUTF8))
        self.RigGroupBox.setTitle(QtGui.QApplication.translate("Form", "Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.FKOnSelection.setToolTip(QtGui.QApplication.translate("Form", "Select some locators in order to create an FK Control", None, QtGui.QApplication.UnicodeUTF8))
        self.FKOnSelection.setText(QtGui.QApplication.translate("Form", "FK on selection", None, QtGui.QApplication.UnicodeUTF8))
        self.IKOnSelection.setToolTip(QtGui.QApplication.translate("Form", "Select some locators in order to create an FK Control", None, QtGui.QApplication.UnicodeUTF8))
        self.IKOnSelection.setText(QtGui.QApplication.translate("Form", "IK on selection", None, QtGui.QApplication.UnicodeUTF8))
        self.GenericJointChainRigBtn.setText(QtGui.QApplication.translate("Form", "Generic Joint Chain Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Progressive Constraint", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.ProgressiveConstraintButton.setText(QtGui.QApplication.translate("Form", "Progressive Constraint", None, QtGui.QApplication.UnicodeUTF8))
        self.mantainOffsetChk.setText(QtGui.QApplication.translate("Form", "mantain offset", None, QtGui.QApplication.UnicodeUTF8))
        self.CnstParentRadio.setText(QtGui.QApplication.translate("Form", "parent", None, QtGui.QApplication.UnicodeUTF8))
        self.CnstOrientRadio.setText(QtGui.QApplication.translate("Form", "orient", None, QtGui.QApplication.UnicodeUTF8))
        self.CnstPointRadio.setText(QtGui.QApplication.translate("Form", "point", None, QtGui.QApplication.UnicodeUTF8))
        self.unfoldRigGrpBox.setTitle(QtGui.QApplication.translate("Form", "Unfold Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.initRadiusLbl.setText(QtGui.QApplication.translate("Form", "Init Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.endRadiusLbl.setText(QtGui.QApplication.translate("Form", "End Radius", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfPointsLbl.setText(QtGui.QApplication.translate("Form", "Number Of Points", None, QtGui.QApplication.UnicodeUTF8))
        self.unfoldRigBtn.setText(QtGui.QApplication.translate("Form", "unfold Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.SkiningToolslabel.setText(QtGui.QApplication.translate("Form", "SkiningTools", None, QtGui.QApplication.UnicodeUTF8))
        self.ListConnectedJoints.setText(QtGui.QApplication.translate("Form", "List Skined Joints", None, QtGui.QApplication.UnicodeUTF8))
        self.SelectJoints.setText(QtGui.QApplication.translate("Form", "Select Joints", None, QtGui.QApplication.UnicodeUTF8))

